#!/bin/sh
# you must call these two before running the script
#voms-proxy-init
#gsido  
version='v5'
cd /hdfs/store/user/tperry/

mkdir ${version}
cd ${version}
mv /scratch/tperry/${version} ./
exit  #leave gsido environment
