#!/bin/sh
# Author: T.M.Perry UW-Madison
# Merges MC samples using farmout (uses mergeFiles.C)

voms-proxy-init --voms cms --valid 100:00

version="post_synch_v0"

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_W1Jet-MuNuPAT_newPAT \
   merged_${version}_W1Jet \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_W2Jet-MuNuPAT_newPAT \
   merged_${version}_W2Jet \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_W3Jet_p1-MuNuPAT_newPAT \
   merged_${version}_W3Jet_p1 \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_W3Jet_p2-MuNuPAT \
   merged_${version}_W3Jet_p2 \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_W4Jet-MuNuPAT \
   merged_${version}_W4Jet \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_WJets-MuNuPAT \
   merged_${version}_WJets \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_TTbar_full-MuNuPAT_newPAT \
   merged_${version}_TTbar_full \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_TTbar_semi-MuNuPAT_newPAT \
   merged_${version}_TTbar_semi \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_Drell-MuNuPAT_newPAT \
   merged_${version}_Drell \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_WW-MuNuPAT_newPAT \
   merged_${version}_WW \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_WZ-MuNuPAT_newPAT \
   merged_${version}_WZ \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_ZZ-MuNuPAT_newPAT \
   merged_${version}_ZZ \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_T_s-MuNuPAT_newPAT \
   merged_${version}_T_s \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_T_t-MuNuPAT_newPAT \
   merged_${version}_T_t \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_T_tW-MuNuPAT_newPAT \
   merged_${version}_T_tW \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_Tbar_s-MuNuPAT_newPAT \
   merged_${version}_Tbar_s \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_Tbar_t-MuNuPAT_newPAT \
   merged_${version}_Tbar_t \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_Tbar_tW-MuNuPAT_newPAT \
   merged_${version}_Tbar_tW \
   $CMSSW_BASE
