#!/bin/sh
# Author: T.M.Perry UW-Madison
# Merges Data samples using farmout (uses mergeFiles.C)

#voms-proxy-init --voms cms --valid 100:00

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_DataA_8TeV-MuNuPATDat \
   merged_${version}_DataA \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_DataB_8TeV-MuNuPATDat \
   merged_${version}_DataB \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_DataC_8TeV-MuNuPATDat \
   merged_${version}_DataC \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_DataD_8TeV-MuNuPATDat \
   merged_${version}_DataD \
   $CMSSW_BASE

