#!/bin/sh
# Author: T.M.Perry UW-Madison
# Merges Data files from /hdfs/... to working directory

version="v5"
cd $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/data/
#mkdir ${version}
cd ${version}

hadd wMuNuData.root \
 /hdfs/store/user/$USER/merged_${version}_DATA1-mergeFilesJob/*.root \
 /hdfs/store/user/$USER/merged_${version}_DATA2-mergeFilesJob/*.root \
 /hdfs/store/user/$USER/merged_${version}_DATA3-mergeFilesJob/*.root \
 /hdfs/store/user/$USER/merged_${version}_DATA4-mergeFilesJob/*.root \
 /hdfs/store/user/$USER/merged_${version}_DATA5-mergeFilesJob/*.root \
 /hdfs/store/user/$USER/merged_${version}_DATA6-mergeFilesJob/*.root 
