#!/bin/sh
# Author: T.M.Perry UW-Madison
# Merges Data samples using farmout (uses mergeFiles.C)

voms-proxy-init --voms cms --valid 100:00

version="v0"

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=500 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_DATA1_8TeV-MuNuPATDat \
   merged_${version}_DATA1 \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=200 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_DATA2_8TeV-MuNuPATDat \
   merged_${version}_DATA2 \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=500 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_DATA3_8TeV-MuNuPATDat \
   merged_${version}_DATA3 \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=500 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_DATA4_8TeV-MuNuPATDat \
   merged_${version}_DATA4 \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=500 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_DATA5_8TeV-MuNuPATDat \
   merged_${version}_DATA5 \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge \
   --input-files-per-job=500 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/${version}_DATA6_8TeV-MuNuPATDat \
   merged_${version}_DATA6 \
   $CMSSW_BASE
