#!/bin/sh
# Author: T.M.Perry UW-Madison
# Moves/Merges MC files from /hdfs/... to working directory


# Drell
farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_Drell-mergeFilesJob \
   mergedFinal_${version}_Drell \
   $CMSSW_BASE

# Single Top

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_T_t-mergeFilesJob \
   mergedFinal_${version}_T_t \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_Tbar_t-mergeFilesJob \
   mergedFinal_${version}_Tbar_t \
   $CMSSW_BASE

# WJets
farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_WJets_p1-mergeFilesJob \
   mergedFinal_${version}_WJets_p1 \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_WJets_p2-mergeFilesJob \
   mergedFinal_${version}_WJets_p2 \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_W1Jet_p1-mergeFilesJob \
   mergedFinal_${version}_W1Jet_p1 \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_W1Jet_p2-mergeFilesJob \
   mergedFinal_${version}_W1Jet_p2 \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_W2Jet_p1-mergeFilesJob \
   mergedFinal_${version}_W2Jet_p1 \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_W2Jet_p2-mergeFilesJob \
   mergedFinal_${version}_W2Jet_p2 \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_W3Jet_p1-mergeFilesJob \
   mergedFinal_${version}_W3Jet_p1 \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_W3Jet_p2-mergeFilesJob \
   mergedFinal_${version}_W3Jet_p2 \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_W4Jet-mergeFilesJob \
   mergedFinal_${version}_W4Jet \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_Wbb4F-mergeFilesJob \
   mergedFinal_${version}_Wbb4F \
   $CMSSW_BASE

# Dibosons
farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_WW-mergeFilesJob \
   mergedFinal_${version}_WW \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_WZ-mergeFilesJob \
   mergedFinal_${version}_WZ \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_ZZ-mergeFilesJob \
   mergedFinal_${version}_ZZ \
   $CMSSW_BASE
