#!/bin/sh

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_DataA-mergeFilesJob \
   mergedFinal_${version}_DataA \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_DataB-mergeFilesJob \
   mergedFinal_${version}_DataB \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_DataC-mergeFilesJob \
   mergedFinal_${version}_DataC \
   $CMSSW_BASE

farmoutAnalysisJobs \
   --merge --use-hadd \
   --input-files-per-job=100 \
   --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tperry/merged_${version}_DataD-mergeFilesJob \
   mergedFinal_${version}_DataD \
   $CMSSW_BASE
