#!/bin/sh
voms-proxy-init --voms cms --valid 100:00

version="v0"

cat MNu-Pat_DATA.py  > MuNuPATDat.py
cat CONDOR_DATA.py >> MuNuPATDat.py

farmoutAnalysisJobs --input-files-per-job=1 --shared-fs \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/SingleMu/Run2012A-13Jul2012-v1/AOD/2013-03-13-8TeV-53X-PatTuple_Master/ \
  ${version}_DATA1_8TeV $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPATDat.py

farmoutAnalysisJobs --input-files-per-job=1 --shared-fs \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/SingleMu/Run2012A-recover-06Aug2012-v1/AOD/2013-03-13-8TeV-53X-PatTuple_Master/ \
  ${version}_DATA2_8TeV $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPATDat.py

farmoutAnalysisJobs --input-files-per-job=1 --shared-fs \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/SingleMu/Run2012B-22Jan2013-v1/AOD/2013-03-13-8TeV-53X-PatTuple_Master/ \
  ${version}_DATA3_8TeV $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPATDat.py

farmoutAnalysisJobs --input-files-per-job=1 --shared-fs \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/SingleMu/Run2012C-24Aug2012-v1/AOD/2013-03-13-8TeV-53X-PatTuple_Master/ \
  ${version}_DATA4_8TeV $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPATDat.py

farmoutAnalysisJobs --input-files-per-job=1 --shared-fs \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/SingleMu/Run2012C-PromptReco-v2/AOD/2013-03-13-8TeV-53X-PatTuple_Master/ \
  ${version}_DATA5_8TeV $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPATDat.py

farmoutAnalysisJobs --input-files-per-job=1 --shared-fs \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/SingleMu/Run2012D-PromptReco-v1/AOD/2013-03-13-8TeV-53X-PatTuple_Master/ \
  ${version}_DATA6_8TeV $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPATDat.py

rm MuNuPATDat.py
