#!/bin/sh
voms-proxy-init --voms cms --valid 100:00

version="v0"

cat MNu-Pat_MC.py  > MuNuPAT.py
cat CONDOR_MC.py >> MuNuPAT.py

cat MNu-Pat_MC_newPAT.py > MuNuPAT_newPAT.py
cat CONDOR_MC.py >> MuNuPAT_newPAT.py

# W Jets
farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/swanson/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_v1_WJets8TeV-9ec8fe3/ \
  ${version}_WJets_p1 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu/store/user/swanson/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball/Summer12_DR53X-PU_S10_START53_V7A-v2/AODSIM/WJetsFarmout/ \
  ${version}_WJets_p2 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

# W1 Jet
farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/swanson/W1JetsToLNu_TuneZ2Star_8TeV-madgraph/W1JetsToLNu_TuneZ2Star_8TeV-madgraph_WJets8TeV-9ec8fe3/ \
  ${version}_W1Jet_josh $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/W1JetsToLNu_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM/2013-06-25-8TeV-53X-PatTuple_Master/ \
  ${version}_W1Jet_tapas $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT_newPAT.py

# W2 Jet
farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/swanson/W2JetsToLNu_TuneZ2Star_8TeV-madgraph/W2JetsToLNu_TuneZ2Star_8TeV-madgraph_WJets8TeV-9ec8fe3/ \
  ${version}_W2Jet_josh $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/W2JetsToLNu_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM/2013-06-25-8TeV-53X-PatTuple_Master \
  ${version}_W2Jet_tapas $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT_newPAT.py

# W3 Jet
farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/swanson/W3JetsToLNu_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM/W3Jets/ \
  ${version}_W3Jet_p1 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT_newPAT.py

farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/swanson/W3JetsToLNu_TuneZ2Star_8TeV-madgraph/W3JetsToLNu_TuneZ2Star_8TeV-madgraph_WJets8TeV-9ec8fe3/ \
  ${version}_W3Jet_p2 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

# W4 Jet
farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/swanson/W4JetsToLNu_TuneZ2Star_8TeV-madgraph/W4JetsToLNu_TuneZ2Star_8TeV-madgraph_WJets8TeV-9ec8fe3/ \
  ${version}_W4Jet $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

# Drell
farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/DYJetsToLL_M-50_TuneZ2Star_8TeV-madgraph-tarball/Summer12_DR53X-PU_S10_START53_V7A-v1/ \
  ${version}_Drell $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

#TTbar
farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/swanson/TTJets_FullLeptMGDecays_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7C-v2/AODSIM/TTBAR/ \
  ${version}_TTbar_full $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/swanson/TTJets_SemiLeptMGDecays_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM/TTBAR/ \
  ${version}_TTbar_semi $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

# Single Top
#tW
farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/Tbar_tW-channel-DR_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/2013-02-25-8TeV-53X-PatTuple_Master/ \
  ${version}_Tbar_tW $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/T_tW-channel-DR_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/2013-02-25-8TeV-53X-PatTuple_Master/ \
  ${version}_T_tW $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

#tt
farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/T_t-channel_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v3/AODSIM/2013-02-25-8TeV-53X-PatTuple_Master/ \
  ${version}_T_t_p1 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/cepeda/T_t-channel_TuneZ2star_8TeV-powheg-tauola/T_t-channel_TuneZ2star_8TeV-powheg-tauola_Take1/ \
  ${version}_T_t_p2 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/Tbar_t-channel_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/2013-02-25-8TeV-53X-PatTuple_Master/ \
 ${version}_Tbar_t $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py
#ts
farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/T_s-channel_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/2013-02-25-8TeV-53X-PatTuple_Master/ \
  ${version}_T_s $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/Tbar_s-channel_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/2013-02-25-8TeV-53X-PatTuple_Master/ \
  ${version}_Tbar_s $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

#Diboson
farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/WW_TuneZ2star_8TeV_pythia6_tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/2013-02-25-8TeV-53X-PatTuple_Master/ \
  ${version}_WW $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/WZ_TuneZ2star_8TeV_pythia6_tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/2013-02-25-8TeV-53X-PatTuple_Master/ \
  ${version}_WZ $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

farmoutAnalysisJobs $1 --input-files-per-job=1 \
  --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/ZZ_TuneZ2star_8TeV_pythia6_tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/2013-02-25-8TeV-53X-PatTuple_Master/ \
  ${version}_ZZ $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

rm MuNuPAT.py
rm MuNuPAT_newPAT.py

