#!/bin/sh
voms-proxy-init --voms cms --valid 100:00

cat MNu-Pat.py  > MuNuPATDat.py
cat CONDOR_DATA.py >> MuNuPATDat.py

farmoutAnalysisJobs --input-files-per-job=1 --lumi-mask=$CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/10_15.json  --shared-fs --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/2012-10-02-8TeV-53X-PatTuple_ShareFSFix/data_SingleMu_Run2012A_13Jul2012_v1/ DATA1_8TeV_sfs $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPATDat.py
farmoutAnalysisJobs --input-files-per-job=1 --lumi-mask=$CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/10_15.json  --shared-fs --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/2012-10-02-8TeV-53X-PatTuple_ShareFSFix/data_SingleMu_Run2012B_13Jul2012_v1/ DATA2_8TeV_sfs $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPATDat.py
farmoutAnalysisJobs --input-files-per-job=1 --lumi-mask=$CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/10_15.json  --shared-fs --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/2012-10-02-8TeV-53X-PatTuple_ShareFSFix/data_SingleMu_Run2012C_PromptReco_v2_Run198934_201264/ DATA3_8TeV_sfs $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPATDat.py
farmoutAnalysisJobs --input-files-per-job=1 --lumi-mask=$CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/10_15.json  --shared-fs --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/2012-10-02-8TeV-53X-PatTuple_ShareFSFix/data_SingleMu_Run2012C_PromptReco_v2_Run201265_203755/ DATA4_8TeV_sfs $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPATDat.py
farmoutAnalysisJobs --input-files-per-job=1 --lumi-mask=$CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/10_15.json  --shared-fs --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/tapas/2012-10-02-8TeV-53X-PatTuple_ShareFSFix/data_SingleMu_Run2012C_24Aug2012_v1/ DATA5_8TeV_sfs $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPATDat.py

rm MuNuPATDat.py
