#!/usr/bin/env python
'''
Makes a root file containing histograms for later plotting
Author: T.M.Perry UW
'''
import ROOT
from ROOT import TGraph,THStack,TLegend,TCanvas,TFile,TH1F, TPad
from ROOT import TLatex
from ROOT import gROOT,gStyle
from ROOT import *

import os

import aHisto as h #function to make histograms
import TheCuts as ct  #function which makes cut strings
import histoRange as hr #manages range, lables for plots
import TheParameters as p

# scale factors : sf_qcd = 1 + (data-allMC)/qcd in 0<mt<20

# Halloween
#sf_qcd = 0.00000000001
#sf_qcd =  # control
#sf_qcd = 0.0025316635942 # Wbb
sf_qcd = 0.00302154299378 # TT_3j
#sf_qcd = 1. # TT_1m1e

sf_drell = 1.
sf_st = 1.   
sf_st_t = 1.
sf_ttbar = 1.
sf_wjets = 1.
sf_vv = 1.

#get parameters (used in cutmaker)
lumi,bNr,btype,jNr,njetcut,jetcut,I,F,iso_value,antiIso_value,path,extraName,leafs,drawW,drawZ,drawQCD,drawData,jetVeto,Control,Z_Region,Legacy,noMT,TT_m,TT_me,ST,Signal,Tomislav,eventTreeLocation,extraCut,Ctl_Andrea = p.arams()
path=path+'Datacard_'

CutsMCn, CutsMCnW, CutsMCi,CutsDatan,CutsDatai,CutsMCnwl,CutsMCiwl,CutsMCnwc,CutsMCiwc,CutsMCnwcc,CutsMCiwcc,CutsMCnwbb,CutsMCiwbb,CutsMCnT,CutsMCiT,CutsMCnTup,CutsMCiTup,CutsMCnTdn,CutsMCiTdn, cutMcNonIso_Bup, cutMcNonIsoW_Bup, cutMcIso_Bup, cutMcWlNonIso_Bup, cutMcWlIso_Bup, cutMcWcNonIso_Bup, cutMcWcIso_Bup, cutMcWccNonIso_Bup, cutMcWccIso_Bup, cutMcWbbNonIso_Bup, cutMcWbbIso_Bup, cutMcNonIso_Bdn, cutMcNonIsoW_Bdn, cutMcIso_Bdn, cutMcWlNonIso_Bdn, cutMcWlIso_Bdn, cutMcWcNonIso_Bdn, cutMcWcIso_Bdn, cutMcWccNonIso_Bdn, cutMcWccIso_Bdn, cutMcWbbNonIso_Bdn, cutMcWbbIso_Bdn = ct.cutmaker(
 leafs[0],iso_value,antiIso_value,lumi,bNr,btype,jNr,njetcut,jetcut,jetVeto,Control,Z_Region,Legacy,noMT,TT_m,TT_me,ST,Signal,Tomislav,extraCut,Ctl_Andrea
)


version = os.environ.get('version')
dpath = "/afs/hep.wisc.edu/cms/tperry/Wbb_CMSSW_5_3_14_patch1/src/UWAnalysis/CRAB/MuNu/data/%s/"%(version)
hpath = "/hdfs/store/user/tperry/%s/"%(version)
npath = "/nfs_scratch/tperry/%s/Filtered_"%(version)
data_filename     = npath+'Data.root'
t_t_filename      = dpath+'T_t.root'
t_s_filename      = npath+'T_s.root'
t_tw_filename     = npath+'T_tW.root'
tb_t_filename     = npath+'Tbar_t.root'
tb_s_filename     = npath+'Tbar_s.root'
tb_tw_filename    = npath+'Tbar_tW.root'
tt_semi_filename  = npath+'TTbar_semi.root'
tt_full_filename  = npath+'TTbar_full.root'
ww_filename       = dpath+'WW.root'
wz_filename       = dpath+'WZ.root'
zz_filename       = dpath+'ZZ.root'
wn_filename       = npath+'WJets.root'
w1_filename       = npath+'W1Jet.root'
w2_filename       = npath+'W2Jet.root'
w3_filename       = npath+'W3Jet.root'
w4_filename       = npath+'W4Jet.root'
z_filename        = dpath+'Drell.root'
w4f_filename      = npath+'Wbb4F.root'

data_file     = TFile( data_filename )
t_t_file      = TFile( t_t_filename  )
t_s_file      = TFile( t_s_filename  )
t_tw_file     = TFile( t_tw_filename )
tb_t_file     = TFile( tb_t_filename )
tb_s_file     = TFile( tb_s_filename )
tb_tw_file    = TFile( tb_tw_filename)
tt_semi_file  = TFile( tt_semi_filename  )
tt_full_file  = TFile( tt_full_filename  )
ww_file       = TFile( ww_filename   )
wz_file       = TFile( wz_filename   )
zz_file       = TFile( zz_filename   )
wn_file       = TFile( wn_filename   )
w1_file       = TFile( w1_filename   )
w2_file       = TFile( w2_filename   )
w3_file       = TFile( w3_filename   )
w4_file       = TFile( w4_filename   )
z_file        = TFile( z_filename    )
w4f_file      = TFile( w4f_filename  )

#Start the Plotting Program
leaf = leafs[0] 
steps, xmin, xmax, xtitle, xunits, setLogY = hr.ranger(leaf)

outFile=gROOT.FindObject(path+extraName+'_'+leaf+'.root')
if outFile : outFile.Close()
outFile = TFile(path+extraName+'_'+leaf+'.root','RECREATE','Demo ROOT file')

log = open(path+extraName+'_'+leaf+'.log','w')


eventTreeLocations = ['muNuEventTree/eventTree',
                      'muNuEventTreeMuonUp/eventTree',
                      'muNuEventTreeMuonDown/eventTree',
                      'muNuEventTreeJetUp/eventTree',
                      'muNuEventTreeJetDown/eventTree',
                      'muNuEventTreeUCEUp/eventTree',
                      'muNuEventTreeUCEDown/eventTree'
                     ]
eventTreeLocations_fltr = ['muNuEventTree_eventTree',
                           'muNuEventTreeMuonUp_eventTree',
                           'muNuEventTreeMuonDown_eventTree',
                           'muNuEventTreeJetUp_eventTree',
                           'muNuEventTreeJetDown_eventTree',
                           'muNuEventTreeUCEUp_eventTree',
                           'muNuEventTreeUCEDown_eventTree'
                          ]
for eventTreeLocation,eventTreeLocation_fltr in zip(eventTreeLocations,eventTreeLocations_fltr):
 
 print('\n\n'+eventTreeLocation)
 data_tree     =  data_file.Get(eventTreeLocation_fltr) 
 t_t_tree      =  t_t_file.Get(eventTreeLocation)
 t_s_tree      =  t_s_file.Get(eventTreeLocation_fltr)
 t_tw_tree     =  t_tw_file.Get(eventTreeLocation_fltr)
 tb_t_tree     =  tb_t_file.Get(eventTreeLocation_fltr)
 tb_s_tree     =  tb_s_file.Get(eventTreeLocation_fltr)
 tb_tw_tree    =  tb_tw_file.Get(eventTreeLocation_fltr)
 tt_semi_tree  =  tt_semi_file.Get(eventTreeLocation_fltr)
 tt_full_tree  =  tt_full_file.Get(eventTreeLocation_fltr)
 ww_tree       =  ww_file.Get(eventTreeLocation)
 wz_tree       =  wz_file.Get(eventTreeLocation)
 zz_tree       =  zz_file.Get(eventTreeLocation)
 wn_tree       =  wn_file.Get(eventTreeLocation_fltr)
 w1_tree       =  w1_file.Get(eventTreeLocation_fltr)
 w2_tree       =  w2_file.Get(eventTreeLocation_fltr)
 w3_tree       =  w3_file.Get(eventTreeLocation_fltr)
 w4_tree       =  w4_file.Get(eventTreeLocation_fltr)
 z_tree        =  z_file.Get(eventTreeLocation)
 w4f_tree      =  w4f_file.Get(eventTreeLocation_fltr)
 
 
 print('----------------------------')
 print('      --'+leaf+'--')
 print(extraName)
 print('----------------------------')
 
 if drawQCD:
  if eventTreeLocation ==  'muNuEventTree/eventTree' :
   ###  DATA 
   datanh,datanhSize,datanhSizePart,datanhEntries = h.gram(data_tree,leaf,xmin,xmax,steps,CutsDatan,I,F)
   print('For QCD Shape')
   print('data nonIso')
   datanh.SetName('datanh')
   print('  '+str(datanhSize))
   print('  '+str(datanhSizePart))

   ### Bup 
  ####  Drell
   print('  z nonIso')
   znhBup,znhBupSize,znhBupSizePart,znhBupEntries = h.gram(z_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bup,I,F)
   znhBup.SetName('znhBup')
   znhBup.Scale(sf_drell)
   print('    '+str(znhBupSize))
   print('    '+str(znhBupSizePart))
  ####  Dibosons
   print('  ww nonIso')
   wwnhBup,wwnhBupSize,wwnhBupSizePart,wwnhBupEntries = h.gram(ww_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bup,I,F)
   wwnhBup.SetName('wwnhBup')
   wwnhBup.Scale(sf_vv)
   print('    '+str(wwnhBupSize))
   print('    '+str(wwnhBupSizePart))
   ###
   print('  wz nonIso')
   wznhBup,wznhBupSize,wznhBupSizePart,wznhBupEntries = h.gram(wz_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bup,I,F)
   wznhBup.SetName('wznhBup')
   wznhBup.Scale(sf_vv)
   print('    '+str(wznhBupSize))
   print('    '+str(wznhBupSizePart))
   ###
   print('  ww nonIso')
   zznhBup,zznhBupSize,zznhBupSizePart,zznhBupEntries = h.gram(zz_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bup,I,F)
   zznhBup.SetName('zznhBup')
   zznhBup.Scale(sf_vv)
   print('    '+str(zznhBupSize))
   print('    '+str(zznhBupSizePart))
  ####  Single Top
   print('  t t nonIso')
   t_tnhBup,t_tnhBupSize,t_tnhBupSizePart,t_tnhBupEntries = h.gram(t_t_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bup,I,F)
   t_tnhBup.SetName('t_tnhBup')
   t_tnhBup.Scale(sf_st_t)
   print('    '+str(t_tnhBupSize))
   print('    '+str(t_tnhBupSizePart))
   ###
   print('  tb t nonIso')
   tb_tnhBup,tb_tnhBupSize,tb_tnhBupSizePart,tb_tnhBupEntries = h.gram(tb_t_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bup,I,F)
   tb_tnhBup.SetName('tb_tnhBup')
   tb_tnhBup.Scale(sf_st)
   print('    '+str(tb_tnhBupSize))
   print('    '+str(tb_tnhBupSizePart))
   ###
   print('  t s nonIso')
   t_snhBup,t_snhBupSize,t_snhBupSizePart,t_snhBupEntries = h.gram(t_s_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bup,I,F)
   t_snhBup.SetName('t_snhBup')
   t_snhBup.Scale(sf_st)
   print('    '+str(t_snhBupSize))
   print('    '+str(t_snhBupSizePart))
   ###
   print('  tb s nonIso')
   tb_snhBup,tb_snhBupSize,tb_snhBupSizePart,tb_snhBupEntries = h.gram(tb_s_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bup,I,F)
   tb_snhBup.SetName('tb_snhBup')
   tb_snhBup.Scale(sf_st)
   print('    '+str(tb_snhBupSize))
   print('    '+str(tb_snhBupSizePart))
   ###
   print('  t tw nonIso')
   t_twnhBup,t_twnhBupSize,t_twnhBupSizePart,t_twnhBupEntries = h.gram(t_tw_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bup,I,F)
   t_twnhBup.SetName('t_twnhBup')
   t_twnhBup.Scale(sf_st)
   print('    '+str(t_twnhBupSize))
   print('    '+str(t_twnhBupSizePart))
   ###
   print('  tb tw nonIso')
   tb_twnhBup,tb_twnhBupSize,tb_twnhBupSizePart,tb_twnhBupEntries = h.gram(tb_tw_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bup,I,F)
   tb_twnhBup.SetName('tb_twnhBup')
   tb_twnhBup.Scale(sf_st)
   print('    '+str(tb_twnhBupSize))
   print('    '+str(tb_twnhBupSizePart))
  ####  TTbar
   print('  ttbar semi nonIso')
   tt_seminhBup,tt_seminhBupSize,tt_seminhBupSizePart,tt_seminhBupEntries = h.gram(tt_semi_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bup,I,F)
   tt_seminhBup.SetName('tt_seminhBup')
   tt_seminhBup.Scale(sf_ttbar)
   print('    '+str(tt_seminhBupSize))
   print('    '+str(tt_seminhBupSizePart))
   print('  ttbar full nonIso')
   tt_fullnhBup,tt_fullnhBupSize,tt_fullnhBupSizePart,tt_fullnhBupEntries = h.gram(tt_full_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bup,I,F)
   tt_fullnhBup.SetName('tt_fullnhBup')
   tt_fullnhBup.Scale(sf_ttbar)
   print('    '+str(tt_fullnhBupSize))
   print('    '+str(tt_fullnhBupSizePart))
  ####  W
   print('  wn nonIso')
   wnnhBup,wnnhBupSize,wnnhBupSizePart,wnhBupEntries = h.gram(wn_tree,leaf,xmin,xmax,steps,cutMcNonIsoW_Bup,I,F)
   wnnhBup.SetName('wnnhBup')
   wnnhBup.Scale(sf_wjets)
   print('    '+str(wnnhBupSize))
   print('    '+str(wnnhBupSizePart))
   print('  w1 nonIso')
   ###
   w1nhBup,w1nhBupSize,w1nhBupSizePart,w1nhBupEntries = h.gram(w1_tree,leaf,xmin,xmax,steps,cutMcNonIsoW_Bup,I,F)
   w1nhBup.SetName('w1nhBup')
   w1nhBup.Scale(sf_wjets)
   print('    '+str(w1nhBupSize))
   print('    '+str(w1nhBupSizePart))
   print('  w2 nonIso')
   ###
   w2nhBup,w2nhBupSize,w2nhBupSizePart,w2nhBupEntries = h.gram(w2_tree,leaf,xmin,xmax,steps,cutMcNonIsoW_Bup,I,F)
   w2nhBup.SetName('w2nhBup')
   w2nhBup.Scale(sf_wjets)
   print('    '+str(w2nhBupSize))
   print('    '+str(w2nhBupSizePart))
   print('  w3 nonIso')
   ###
   w3nhBup,w3nhBupSize,w3nhBupSizePart,w3nhBupEntries = h.gram(w3_tree,leaf,xmin,xmax,steps,cutMcNonIsoW_Bup,I,F)
   w3nhBup.SetName('w3nhBup')
   w3nhBup.Scale(sf_wjets)
   print('    '+str(w3nhBupSize))
   print('    '+str(w3nhBupSizePart))
   print('  w4 nonIso')
   ###
   w4nhBup,w4nhBupSize,w4nhBupSizePart,w4nhBupEntries = h.gram(w4_tree,leaf,xmin,xmax,steps,cutMcNonIsoW_Bup,I,F)
   w4nhBup.SetName('w4nhBup')
   w4nhBup.Scale(sf_wjets)
   print('    '+str(w4nhBupSize))
   print('    '+str(w4nhBupSizePart))

   ### Bdn
  ####  Drell
   print('  z nonIso')
   znhBdn,znhBdnSize,znhBdnSizePart,znhBdnEntries = h.gram(z_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bdn,I,F)
   znhBdn.SetName('znhBdn')
   znhBdn.Scale(sf_drell)
   print('    '+str(znhBdnSize))
   print('    '+str(znhBdnSizePart))
  ####  Dibosons
   print('  ww nonIso')
   wwnhBdn,wwnhBdnSize,wwnhBdnSizePart,wwnhBdnEntries = h.gram(ww_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bdn,I,F)
   wwnhBdn.SetName('wwnhBdn')
   wwnhBdn.Scale(sf_vv)
   print('    '+str(wwnhBdnSize))
   print('    '+str(wwnhBdnSizePart))
   ###
   print('  wz nonIso')
   wznhBdn,wznhBdnSize,wznhBdnSizePart,wznhBdnEntries = h.gram(wz_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bdn,I,F)
   wznhBdn.SetName('wznhBdn')
   wznhBdn.Scale(sf_vv)
   print('    '+str(wznhBdnSize))
   print('    '+str(wznhBdnSizePart))
   ###
   print('  ww nonIso')
   zznhBdn,zznhBdnSize,zznhBdnSizePart,zznhBdnEntries = h.gram(zz_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bdn,I,F)
   zznhBdn.SetName('zznhBdn')
   zznhBdn.Scale(sf_vv)
   print('    '+str(zznhBdnSize))
   print('    '+str(zznhBdnSizePart))
  ####  Single Top
   print('  t t nonIso')
   t_tnhBdn,t_tnhBdnSize,t_tnhBdnSizePart,t_tnhBdnEntries = h.gram(t_t_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bdn,I,F)
   t_tnhBdn.SetName('t_tnhBdn')
   t_tnhBdn.Scale(sf_st_t)
   print('    '+str(t_tnhBdnSize))
   print('    '+str(t_tnhBdnSizePart))
   ###
   print('  tb t nonIso')
   tb_tnhBdn,tb_tnhBdnSize,tb_tnhBdnSizePart,tb_tnhBdnEntries = h.gram(tb_t_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bdn,I,F)
   tb_tnhBdn.SetName('tb_tnhBdn')
   tb_tnhBdn.Scale(sf_st)
   print('    '+str(tb_tnhBdnSize))
   print('    '+str(tb_tnhBdnSizePart))
   ###
   print('  t s nonIso')
   t_snhBdn,t_snhBdnSize,t_snhBdnSizePart,t_snhBdnEntries = h.gram(t_s_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bdn,I,F)
   t_snhBdn.SetName('t_snhBdn')
   t_snhBdn.Scale(sf_st)
   print('    '+str(t_snhBdnSize))
   print('    '+str(t_snhBdnSizePart))
   ###
   print('  tb s nonIso')
   tb_snhBdn,tb_snhBdnSize,tb_snhBdnSizePart,tb_snhBdnEntries = h.gram(tb_s_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bdn,I,F)
   tb_snhBdn.SetName('tb_snhBdn')
   tb_snhBdn.Scale(sf_st)
   print('    '+str(tb_snhBdnSize))
   print('    '+str(tb_snhBdnSizePart))
   ###
   print('  t tw nonIso')
   t_twnhBdn,t_twnhBdnSize,t_twnhBdnSizePart,t_twnhBdnEntries = h.gram(t_tw_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bdn,I,F)
   t_twnhBdn.SetName('t_twnhBdn')
   t_twnhBdn.Scale(sf_st)
   print('    '+str(t_twnhBdnSize))
   print('    '+str(t_twnhBdnSizePart))
   ###
   print('  tb tw nonIso')
   tb_twnhBdn,tb_twnhBdnSize,tb_twnhBdnSizePart,tb_twnhBdnEntries = h.gram(tb_tw_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bdn,I,F)
   tb_twnhBdn.SetName('tb_twnhBdn')
   tb_twnhBdn.Scale(sf_st)
   print('    '+str(tb_twnhBdnSize))
   print('    '+str(tb_twnhBdnSizePart))
  ####  TTbar
   print('  ttbar semi nonIso')
   tt_seminhBdn,tt_seminhBdnSize,tt_seminhBdnSizePart,tt_seminhBdnEntries = h.gram(tt_semi_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bdn,I,F)
   tt_seminhBdn.SetName('tt_seminhBdn')
   tt_seminhBdn.Scale(sf_ttbar)
   print('    '+str(tt_seminhBdnSize))
   print('    '+str(tt_seminhBdnSizePart))
   print('  ttbar full nonIso')
   tt_fullnhBdn,tt_fullnhBdnSize,tt_fullnhBdnSizePart,tt_fullnhBdnEntries = h.gram(tt_full_tree,leaf,xmin,xmax,steps,cutMcNonIso_Bdn,I,F)
   tt_fullnhBdn.SetName('tt_fullnhBdn')
   tt_fullnhBdn.Scale(sf_ttbar)
   print('    '+str(tt_fullnhBdnSize))
   print('    '+str(tt_fullnhBdnSizePart))
  ####  W
   print('  wn nonIso')
   wnnhBdn,wnnhBdnSize,wnnhBdnSizePart,wnhBdnEntries = h.gram(wn_tree,leaf,xmin,xmax,steps,cutMcNonIsoW_Bdn,I,F)
   wnnhBdn.SetName('wnnhBdn')
   wnnhBdn.Scale(sf_wjets)
   print('    '+str(wnnhBdnSize))
   print('    '+str(wnnhBdnSizePart))
   print('  w1 nonIso')
   ###
   w1nhBdn,w1nhBdnSize,w1nhBdnSizePart,w1nhBdnEntries = h.gram(w1_tree,leaf,xmin,xmax,steps,cutMcNonIsoW_Bdn,I,F)
   w1nhBdn.SetName('w1nhBdn')
   w1nhBdn.Scale(sf_wjets)
   print('    '+str(w1nhBdnSize))
   print('    '+str(w1nhBdnSizePart))
   print('  w2 nonIso')
   ###
   w2nhBdn,w2nhBdnSize,w2nhBdnSizePart,w2nhBdnEntries = h.gram(w2_tree,leaf,xmin,xmax,steps,cutMcNonIsoW_Bdn,I,F)
   w2nhBdn.SetName('w2nhBdn')
   w2nhBdn.Scale(sf_wjets)
   print('    '+str(w2nhBdnSize))
   print('    '+str(w2nhBdnSizePart))
   print('  w3 nonIso')
   ###
   w3nhBdn,w3nhBdnSize,w3nhBdnSizePart,w3nhBdnEntries = h.gram(w3_tree,leaf,xmin,xmax,steps,cutMcNonIsoW_Bdn,I,F)
   w3nhBdn.SetName('w3nhBdn')
   w3nhBdn.Scale(sf_wjets)
   print('    '+str(w3nhBdnSize))
   print('    '+str(w3nhBdnSizePart))
   print('  w4 nonIso')
   ###
   w4nhBdn,w4nhBdnSize,w4nhBdnSizePart,w4nhBdnEntries = h.gram(w4_tree,leaf,xmin,xmax,steps,cutMcNonIsoW_Bdn,I,F)
   w4nhBdn.SetName('w4nhBdn')
   w4nhBdn.Scale(sf_wjets)
   print('    '+str(w4nhBdnSize))
   print('    '+str(w4nhBdnSizePart))

 ####  Drell
  print('  z nonIso')
  znh,znhSize,znhSizePart,znhEntries = h.gram(z_tree,leaf,xmin,xmax,steps,CutsMCn,I,F)
  znh.SetName('znh')
  znh.Scale(sf_drell)
  print('    '+str(znhSize))
  print('    '+str(znhSizePart))
 ####  Dibosons
  print('  ww nonIso')
  wwnh,wwnhSize,wwnhSizePart,wwnhEntries = h.gram(ww_tree,leaf,xmin,xmax,steps,CutsMCn,I,F)
  wwnh.SetName('wwnh')
  wwnh.Scale(sf_vv)
  print('    '+str(wwnhSize))
  print('    '+str(wwnhSizePart))
  ###
  print('  wz nonIso')
  wznh,wznhSize,wznhSizePart,wznhEntries = h.gram(wz_tree,leaf,xmin,xmax,steps,CutsMCn,I,F)
  wznh.SetName('wznh')
  wznh.Scale(sf_vv)
  print('    '+str(wznhSize))
  print('    '+str(wznhSizePart))
  ###
  print('  ww nonIso')
  zznh,zznhSize,zznhSizePart,zznhEntries = h.gram(zz_tree,leaf,xmin,xmax,steps,CutsMCn,I,F)
  zznh.SetName('zznh')
  zznh.Scale(sf_vv)
  print('    '+str(zznhSize))
  print('    '+str(zznhSizePart))
 ####  Single Top
  print('  t t nonIso')
  t_tnh,t_tnhSize,t_tnhSizePart,t_tnhEntries = h.gram(t_t_tree,leaf,xmin,xmax,steps,CutsMCn,I,F)
  t_tnh.SetName('t_tnh')
  t_tnh.Scale(sf_st_t)
  print('    '+str(t_tnhSize))
  print('    '+str(t_tnhSizePart))
  ###
  print('  tb t nonIso')
  tb_tnh,tb_tnhSize,tb_tnhSizePart,tb_tnhEntries = h.gram(tb_t_tree,leaf,xmin,xmax,steps,CutsMCn,I,F)
  tb_tnh.SetName('tb_tnh')
  tb_tnh.Scale(sf_st)
  print('    '+str(tb_tnhSize))
  print('    '+str(tb_tnhSizePart))
  ###
  print('  t s nonIso')
  t_snh,t_snhSize,t_snhSizePart,t_snhEntries = h.gram(t_s_tree,leaf,xmin,xmax,steps,CutsMCn,I,F)
  t_snh.SetName('t_snh')
  t_snh.Scale(sf_st)
  print('    '+str(t_snhSize))
  print('    '+str(t_snhSizePart))
  ###
  print('  tb s nonIso')
  tb_snh,tb_snhSize,tb_snhSizePart,tb_snhEntries = h.gram(tb_s_tree,leaf,xmin,xmax,steps,CutsMCn,I,F)
  tb_snh.SetName('tb_snh')
  tb_snh.Scale(sf_st)
  print('    '+str(tb_snhSize))
  print('    '+str(tb_snhSizePart))
  ###
  print('  t tw nonIso')
  t_twnh,t_twnhSize,t_twnhSizePart,t_twnhEntries = h.gram(t_tw_tree,leaf,xmin,xmax,steps,CutsMCn,I,F)
  t_twnh.SetName('t_twnh')
  t_twnh.Scale(sf_st)
  print('    '+str(t_twnhSize))
  print('    '+str(t_twnhSizePart))
  ###
  print('  tb tw nonIso')
  tb_twnh,tb_twnhSize,tb_twnhSizePart,tb_twnhEntries = h.gram(tb_tw_tree,leaf,xmin,xmax,steps,CutsMCn,I,F)
  tb_twnh.SetName('tb_twnh')
  tb_twnh.Scale(sf_st)
  print('    '+str(tb_twnhSize))
  print('    '+str(tb_twnhSizePart))
 ####  TTbar
  print('  ttbar semi nonIso')
  tt_seminh,tt_seminhSize,tt_seminhSizePart,tt_seminhEntries = h.gram(tt_semi_tree,leaf,xmin,xmax,steps,CutsMCnT,I,F)
  tt_seminh.SetName('tt_seminh')
  tt_seminh.Scale(sf_ttbar)
  print('    '+str(tt_seminhSize))
  print('    '+str(tt_seminhSizePart))
  print('  ttbar full nonIso')
  tt_fullnh,tt_fullnhSize,tt_fullnhSizePart,tt_fullnhEntries = h.gram(tt_full_tree,leaf,xmin,xmax,steps,CutsMCnT,I,F)
  tt_fullnh.SetName('tt_fullnh')
  tt_fullnh.Scale(sf_ttbar)
  print('    '+str(tt_fullnhSize))
  print('    '+str(tt_fullnhSizePart))
  if eventTreeLocation ==  'muNuEventTree/eventTree' :
   print('  ttbar semi nonIso Up')
   tt_seminhUp,tt_seminhSizeUp,tt_seminhSizePartUp,tt_seminhEntriesUp = h.gram(tt_semi_tree,leaf,xmin,xmax,steps,CutsMCnTup,I,F)
   tt_seminhUp.SetName('tt_seminhUp')
   tt_seminhUp.Scale(sf_ttbar)
   print('    '+str(tt_seminhSizeUp))
   print('    '+str(tt_seminhSizePartUp))
   print('  ttbar full nonIso Up')
   tt_fullnhUp,tt_fullnhSizeUp,tt_fullnhSizePartUp,tt_fullnhEntriesUp = h.gram(tt_full_tree,leaf,xmin,xmax,steps,CutsMCnTup,I,F)
   tt_fullnhUp.SetName('tt_fullnhUp')
   tt_fullnhUp.Scale(sf_ttbar)
   print('    '+str(tt_fullnhSizeUp))
   print('    '+str(tt_fullnhSizePartUp))

   print('  ttbar semi nonIso Dn')
   tt_seminhDn,tt_seminhSizeDn,tt_seminhSizePartDn,tt_seminhEntriesDn = h.gram(tt_semi_tree,leaf,xmin,xmax,steps,CutsMCnTdn,I,F)
   tt_seminhDn.SetName('tt_seminhDn')
   tt_seminhDn.Scale(sf_ttbar)
   print('    '+str(tt_seminhSizeDn))
   print('    '+str(tt_seminhSizePartDn))
   print('  ttbar full nonIso Dn')
   tt_fullnhDn,tt_fullnhSizeDn,tt_fullnhSizePartDn,tt_fullnhEntriesDn = h.gram(tt_full_tree,leaf,xmin,xmax,steps,CutsMCnTdn,I,F)
   tt_fullnhDn.SetName('tt_fullnhDn')
   tt_fullnhDn.Scale(sf_ttbar)
   print('    '+str(tt_fullnhSizeDn))
   print('    '+str(tt_fullnhSizePartDn))

 ####  W
  print('  wn nonIso')
  wnnh,wnnhSize,wnnhSizePart,wnhEntries = h.gram(wn_tree,leaf,xmin,xmax,steps,CutsMCnW,I,F)
  wnnh.SetName('wnnh')
  wnnh.Scale(sf_wjets)
  print('    '+str(wnnhSize))
  print('    '+str(wnnhSizePart))
  print('  w1 nonIso')
  ###
  w1nh,w1nhSize,w1nhSizePart,w1nhEntries = h.gram(w1_tree,leaf,xmin,xmax,steps,CutsMCnW,I,F)
  w1nh.SetName('w1nh')
  w1nh.Scale(sf_wjets)
  print('    '+str(w1nhSize))
  print('    '+str(w1nhSizePart))
  print('  w2 nonIso')
  ###
  w2nh,w2nhSize,w2nhSizePart,w2nhEntries = h.gram(w2_tree,leaf,xmin,xmax,steps,CutsMCnW,I,F)
  w2nh.SetName('w2nh')
  w2nh.Scale(sf_wjets)
  print('    '+str(w2nhSize))
  print('    '+str(w2nhSizePart))
  print('  w3 nonIso')
  ###
  w3nh,w3nhSize,w3nhSizePart,w3nhEntries = h.gram(w3_tree,leaf,xmin,xmax,steps,CutsMCnW,I,F)
  w3nh.SetName('w3nh')
  w3nh.Scale(sf_wjets)
  print('    '+str(w3nhSize))
  print('    '+str(w3nhSizePart))
  print('  w4 nonIso')
  ###
  w4nh,w4nhSize,w4nhSizePart,w4nhEntries = h.gram(w4_tree,leaf,xmin,xmax,steps,CutsMCnW,I,F)
  w4nh.SetName('w4nh')
  w4nh.Scale(sf_wjets)
  print('    '+str(w4nhSize))
  print('    '+str(w4nhSizePart))
 #
  print('subtracting non-iso MC from Data ')
  qh = datanh.Clone()
  qh.SetName('qh')
  qh.Add(znh,-1)    #Drell
  qh.Add(t_tnh,-1)  #Single Top
  qh.Add(tb_tnh,-1)
  qh.Add(t_snh,-1)
  qh.Add(tb_snh,-1)
  qh.Add(t_twnh,-1)
  qh.Add(tb_twnh,-1)
  qh.Add(wwnh,-1)   #Diboson
  qh.Add(wznh,-1)
  qh.Add(zznh,-1)
  qh.Add(tt_seminh,-1)  #TTbar
  qh.Add(tt_fullnh,-1)  #TTbar
  qh.Add(wnnh,-1)   #W
  qh.Add(w1nh,-1)
  qh.Add(w2nh,-1)
  qh.Add(w3nh,-1)
  qh.Add(w4nh,-1)
  print('     QCD: %0.2f'%(qh.Integral()))
 
  if eventTreeLocation ==  'muNuEventTree/eventTree' :
   qhTup = datanh.Clone()
   qhTup.SetName('qhTup')
   qhTup.Add(znh,-1)    #Drell
   qhTup.Add(t_tnh,-1)  #Single Top
   qhTup.Add(tb_tnh,-1)
   qhTup.Add(t_snh,-1)
   qhTup.Add(tb_snh,-1)
   qhTup.Add(t_twnh,-1)
   qhTup.Add(tb_twnh,-1)
   qhTup.Add(wwnh,-1)   #Diboson
   qhTup.Add(wznh,-1)
   qhTup.Add(zznh,-1)
   qhTup.Add(tt_seminhUp,-1)  #TTbar
   qhTup.Add(tt_fullnhUp,-1)  #TTbar
   qhTup.Add(wnnh,-1)   #W
   qhTup.Add(w1nh,-1)
   qhTup.Add(w2nh,-1)
   qhTup.Add(w3nh,-1)
   qhTup.Add(w4nh,-1)

   qhTdn = datanh.Clone()
   qhTdn.SetName('qhTdn')
   qhTdn.Add(znh,-1)    #Drell
   qhTdn.Add(t_tnh,-1)  #Single Top
   qhTdn.Add(tb_tnh,-1)
   qhTdn.Add(t_snh,-1)
   qhTdn.Add(tb_snh,-1)
   qhTdn.Add(t_twnh,-1)
   qhTdn.Add(tb_twnh,-1)
   qhTdn.Add(wwnh,-1)   #Diboson
   qhTdn.Add(wznh,-1)
   qhTdn.Add(zznh,-1)
   qhTdn.Add(tt_seminhDn,-1)  #TTbar
   qhTdn.Add(tt_fullnhDn,-1)  #TTbar
   qhTdn.Add(wnnh,-1)   #W
   qhTdn.Add(w1nh,-1)
   qhTdn.Add(w2nh,-1)
   qhTdn.Add(w3nh,-1)
   qhTdn.Add(w4nh,-1)

   QCD_BeffUp = datanh.Clone()
   QCD_BeffUp.SetName('QCD_BeffUp')
   QCD_BeffUp.Add(znhBup,-1)    #Drell
   QCD_BeffUp.Add(t_tnhBup,-1)  #Single Top
   QCD_BeffUp.Add(tb_tnhBup,-1)
   QCD_BeffUp.Add(t_snhBup,-1)
   QCD_BeffUp.Add(tb_snhBup,-1)
   QCD_BeffUp.Add(t_twnhBup,-1)
   QCD_BeffUp.Add(tb_twnhBup,-1)
   QCD_BeffUp.Add(wwnhBup,-1)   #Diboson
   QCD_BeffUp.Add(wznhBup,-1)
   QCD_BeffUp.Add(zznhBup,-1)
   QCD_BeffUp.Add(tt_seminhBup,-1)  #TTbar
   QCD_BeffUp.Add(tt_fullnhBup,-1)  #TTbar
   QCD_BeffUp.Add(wnnhBup,-1)   #W
   QCD_BeffUp.Add(w1nhBup,-1)
   QCD_BeffUp.Add(w2nhBup,-1)
   QCD_BeffUp.Add(w3nhBup,-1)
   QCD_BeffUp.Add(w4nhBup,-1)

   QCD_BeffDown = datanh.Clone()
   QCD_BeffDown.SetName('QCD_BeffDown')
   QCD_BeffDown.Add(znhBdn,-1)    #Drell
   QCD_BeffDown.Add(t_tnhBdn,-1)  #Single Top
   QCD_BeffDown.Add(tb_tnhBdn,-1)
   QCD_BeffDown.Add(t_snhBdn,-1)
   QCD_BeffDown.Add(tb_snhBdn,-1)
   QCD_BeffDown.Add(t_twnhBdn,-1)
   QCD_BeffDown.Add(tb_twnhBdn,-1)
   QCD_BeffDown.Add(wwnhBdn,-1)   #Diboson
   QCD_BeffDown.Add(wznhBdn,-1)
   QCD_BeffDown.Add(zznhBdn,-1)
   QCD_BeffDown.Add(tt_seminhBdn,-1)  #TTbar
   QCD_BeffDown.Add(tt_fullnhBdn,-1)  #TTbar
   QCD_BeffDown.Add(wnnhBdn,-1)   #W
   QCD_BeffDown.Add(w1nhBdn,-1)
   QCD_BeffDown.Add(w2nhBdn,-1)
   QCD_BeffDown.Add(w3nhBdn,-1)
   QCD_BeffDown.Add(w4nhBdn,-1)

  print('qcd')
  qh.SetTitle('')
  bminq = qh.GetXaxis().FindBin(xmin)
  bmaxq = qh.GetXaxis().FindBin(xmax)
  bIq = qh.GetXaxis().FindBin(I)
  bFq = qh.GetXaxis().FindBin(F)
  qhSizePart = qh.Integral(bIq,bFq)
  qh.Scale(sf_qcd)
  qhSize = qh.Integral(bminq,bmaxq)
  qhEntries = qh.GetEntries()
  print('  '+str(qhSize))
  print('  '+str(qhSizePart))
 ####################################
 if drawData and  eventTreeLocation == 'muNuEventTree/eventTree':
  ### Data
  print('')
  print('Isolated Variables Now')
  print("data Iso") 
  dataih,dataihSize,dataihSizePart,dataihEntries = h.gram(data_tree,leaf,xmin,xmax,steps,CutsDatai,I,F)
  dataih.SetName('dataih')
  print('  '+str(dataihSize))
  print('  '+str(dataihSizePart))
  dimax = dataih.GetMaximum()

 ## B Up
 #### Drell
  print("z Iso")
  zihBup,zihBupSize,zihBupSizePart,zihBupEntries = h.gram(z_tree,leaf,xmin,xmax,steps,cutMcIso_Bup,I,F)
  zihBup.SetName('zihBup')
  zihBup.Scale(sf_drell)
  print('  '+str(zihBupSize))
  print('  '+str(zihBupSizePart))
 #### Diboson
  print("ww Iso")
  wwihBup,wwihBupSize,wwihBupSizePart,wwihBupEntries = h.gram(ww_tree,leaf,xmin,xmax,steps,cutMcIso_Bup,I,F)
  wwihBup.SetName('wwihBup')
  wwihBup.Scale(sf_vv)
  print('  '+str(wwihBupSize))
  print('  '+str(wwihBupSizePart))
  ###
  print("wz Iso")
  wzihBup,wzihBupSize,wzihBupSizePart,wzihBupEntries = h.gram(wz_tree,leaf,xmin,xmax,steps,cutMcIso_Bup,I,F)
  wzihBup.SetName('wzihBup')
  wzihBup.Scale(sf_vv)
  print('  '+str(wzihBupSize))
  print('  '+str(wzihBupSizePart))
  ###
  print("zz Iso")
  zzihBup,zzihBupSize,zzihBupSizePart,zzihBupEntries = h.gram(zz_tree,leaf,xmin,xmax,steps,cutMcIso_Bup,I,F)
  zzihBup.SetName('zzihBup')
  zzihBup.Scale(sf_vv)
  print('  '+str(zzihBupSize))
  print('  '+str(zzihBupSizePart))
 #### Single Top
  print('t t Iso')
  t_tihBup,t_tihBupSize,t_tihBupSizePart,t_tihBupEntries = h.gram(t_t_tree,leaf,xmin,xmax,steps,cutMcIso_Bup,I,F)
  t_tihBup.SetName('t_tihBup')
  t_tihBup.Scale(sf_st_t)
  print('  '+str(t_tihBupSize))
  print('  '+str(t_tihBupSizePart))
  ###
  print('tb t Iso')
  tb_tihBup,tb_tihBupSize,tb_tihBupSizePart,tb_tihBupEntries = h.gram(tb_t_tree,leaf,xmin,xmax,steps,cutMcIso_Bup,I,F)
  tb_tihBup.SetName('tb_tihBup')
  tb_tihBup.Scale(sf_st)
  print('  '+str(tb_tihBupSize))
  print('  '+str(tb_tihBupSizePart))
  ###
  print('t s Iso')
  t_sihBup,t_sihBupSize,t_sihBupSizePart,t_sihBupEntries = h.gram(t_s_tree,leaf,xmin,xmax,steps,cutMcIso_Bup,I,F)
  t_sihBup.SetName('t_sihBup')
  t_sihBup.Scale(sf_st)
  print('  '+str(t_sihBupSize))
  print('  '+str(t_sihBupSizePart))
  ###
  print('tb s Iso')
  tb_sihBup,tb_sihBupSize,tb_sihBupSizePart,tb_sihBupEntries = h.gram(tb_s_tree,leaf,xmin,xmax,steps,cutMcIso_Bup,I,F)
  tb_sihBup.SetName('tb_sihBup')
  tb_sihBup.Scale(sf_st)
  print('  '+str(tb_sihBupSize))
  print('  '+str(tb_sihBupSizePart))
  ###
  print('t tw Iso')
  t_twihBup,t_twihBupSize,t_twihBupSizePart,t_twihBupEntries = h.gram(t_tw_tree,leaf,xmin,xmax,steps,cutMcIso_Bup,I,F)
  t_twihBup.SetName('t_twihBup')
  t_twihBup.Scale(sf_st)
  print('  '+str(t_twihBupSize))
  print('  '+str(t_twihBupSizePart))
  ###
  print('tb tw Iso')
  tb_twihBup,tb_twihBupSize,tb_twihBupSizePart,tb_twihBupEntries = h.gram(tb_tw_tree,leaf,xmin,xmax,steps,cutMcIso_Bup,I,F)
  tb_twihBup.SetName('tb_twihBup')
  tb_twihBup.Scale(sf_st)
  print('  '+str(tb_twihBupSize))
  print('  '+str(tb_twihBupSizePart))
 #### TTbar
  print('ttb semi Iso')
  tt_semiihBup,tt_semiihBupSize,tt_semiihBupSizePart,tt_semiihBupEntries = h.gram(tt_semi_tree,leaf,xmin,xmax,steps,cutMcIso_Bup,I,F)
  tt_semiihBup.SetName('tt_semiihBup')
  tt_semiihBup.Scale(sf_ttbar)
  print('  '+str(tt_semiihBupSize))
  print('  '+str(tt_semiihBupSizePart))
  print('ttb full Iso')
  tt_fullihBup,tt_fullihBupSize,tt_fullihBupSizePart,tt_fullihBupEntries = h.gram(tt_full_tree,leaf,xmin,xmax,steps,cutMcIso_Bup,I,F)
  tt_fullihBup.SetName('tt_fullihBup')
  tt_fullihBup.Scale(sf_ttbar)
  print('  '+str(tt_fullihBupSize))
  print('  '+str(tt_fullihBupSizePart))
 
 #### W + Jets
  print('wl n Iso')
  wlnihBup,wlnihBupSize,wlnihBupSizePart,wlnihBupEntries = h.gram(wn_tree,leaf,xmin,xmax,steps,cutMcWlIso_Bup,I,F)
  wlnihBup.SetName('wlnihBup')
  wlnihBup.Scale(sf_wjets)
  print('  '+str(wlnihBupSize))
  print('  '+str(wlnihBupSizePart))
  ####
  print('wc n Iso')
  wcnihBup,wcnihBupSize,wcnihBupSizePart,wcnihBupEntries = h.gram(wn_tree,leaf,xmin,xmax,steps,cutMcWcIso_Bup,I,F)
  wcnihBup.SetName('wcnihBup')
  wcnihBup.Scale(sf_wjets)
  print('  '+str(wcnihBupSize))
  print('  '+str(wcnihBupSizePart))
  ####
  print('wcc n Iso')
  wccnihBup,wccnihBupSize,wccnihBupSizePart,wccnihBupEntries = h.gram(wn_tree,leaf,xmin,xmax,steps,cutMcWccIso_Bup,I,F)
  wccnihBup.SetName('wccnihBup')
  wccnihBup.Scale(sf_wjets)
  print('  '+str(wccnihBupSize))
  print('  '+str(wccnihBupSizePart))
  ####
  print('wbb n Iso')
  wbbnihBup,wbbnihBupSize,wbbnihBupSizePart,wbbnihBupEntries = h.gram(wn_tree,leaf,xmin,xmax,steps,cutMcWbbIso_Bup,I,F)
  wbbnihBup.SetName('wbbnihBup')
  wbbnihBup.Scale(sf_wjets)
  print('  '+str(wbbnihBupSize))
  print('  '+str(wbbnihBupSizePart))
 #####
  print('wl 1 Iso')
  wl1ihBup,wl1ihBupSize,wl1ihBupSizePart,wl1ihBupEntries = h.gram(w1_tree,leaf,xmin,xmax,steps,cutMcWlIso_Bup,I,F)
  wl1ihBup.SetName('wl1ihBup')
  wl1ihBup.Scale(sf_wjets)
  print('  '+str(wl1ihBupSize))
  print('  '+str(wl1ihBupSizePart))
  ####
  print('wc 1 Iso')
  wc1ihBup,wc1ihBupSize,wc1ihBupSizePart,wc1ihBupEntries = h.gram(w1_tree,leaf,xmin,xmax,steps,cutMcWcIso_Bup,I,F)
  wc1ihBup.SetName('wc1ihBup')
  wc1ihBup.Scale(sf_wjets)
  print('  '+str(wc1ihBupSize))
  print('  '+str(wc1ihBupSizePart))
  ####
  print('wcc 1 Iso')
  wcc1ihBup,wcc1ihBupSize,wcc1ihBupSizePart,wcc1ihBupEntries = h.gram(w1_tree,leaf,xmin,xmax,steps,cutMcWccIso_Bup,I,F)
  wcc1ihBup.SetName('wcc1ihBup')
  wcc1ihBup.Scale(sf_wjets)
  print('  '+str(wcc1ihBupSize))
  print('  '+str(wcc1ihBupSizePart))
  ####
  print('wbb 1 Iso')
  wbb1ihBup,wbb1ihBupSize,wbb1ihBupSizePart,wbb1ihBupEntries = h.gram(w1_tree,leaf,xmin,xmax,steps,cutMcWbbIso_Bup,I,F)
  wbb1ihBup.SetName('wbb1ihBup')
  wbb1ihBup.Scale(sf_wjets)
  print('  '+str(wbb1ihBupSize))
  print('  '+str(wbb1ihBupSizePart))
 #####
  print('wl 2 Iso')
  wl2ihBup,wl2ihBupSize,wl2ihBupSizePart,wl2ihBupEntries = h.gram(w2_tree,leaf,xmin,xmax,steps,cutMcWlIso_Bup,I,F)
  wl2ihBup.SetName('wl2ihBup')
  wl2ihBup.Scale(sf_wjets)
  print('  '+str(wl2ihBupSize))
  print('  '+str(wl2ihBupSizePart))
  ####
  print('wc 2 Iso')
  wc2ihBup,wc2ihBupSize,wc2ihBupSizePart,wc2ihBupEntries = h.gram(w2_tree,leaf,xmin,xmax,steps,cutMcWcIso_Bup,I,F)
  wc2ihBup.SetName('wc2ihBup')
  wc2ihBup.Scale(sf_wjets)
  print('  '+str(wc2ihBupSize))
  print('  '+str(wc2ihBupSizePart))
  ####
  print('wcc 2 Iso')
  wcc2ihBup,wcc2ihBupSize,wcc2ihBupSizePart,wcc2ihBupEntries = h.gram(w2_tree,leaf,xmin,xmax,steps,cutMcWccIso_Bup,I,F)
  wcc2ihBup.SetName('wcc2ihBup')
  wcc2ihBup.Scale(sf_wjets)
  print('  '+str(wcc2ihBupSize))
  print('  '+str(wcc2ihBupSizePart))
  ####
  print('wbb 2 Iso')
  wbb2ihBup,wbb2ihBupSize,wbb2ihBupSizePart,wbb2ihBupEntries = h.gram(w2_tree,leaf,xmin,xmax,steps,cutMcWbbIso_Bup,I,F)
  wbb2ihBup.SetName('wbb2ihBup')
  wbb2ihBup.Scale(sf_wjets)
  print('  '+str(wbb2ihBupSize))
  print('  '+str(wbb2ihBupSizePart))
 #####
  print('wl 3 Iso')
  wl3ihBup,wl3ihBupSize,wl3ihBupSizePart,wl3ihBupEntries = h.gram(w3_tree,leaf,xmin,xmax,steps,cutMcWlIso_Bup,I,F)
  wl3ihBup.SetName('wl3ihBup')
  wl3ihBup.Scale(sf_wjets)
  print('  '+str(wl3ihBupSize))
  print('  '+str(wl3ihBupSizePart))
  ####
  print('wc 3 Iso')
  wc3ihBup,wc3ihBupSize,wc3ihBupSizePart,wc3ihBupEntries = h.gram(w3_tree,leaf,xmin,xmax,steps,cutMcWcIso_Bup,I,F)
  wc3ihBup.SetName('wc3ihBup')
  wc3ihBup.Scale(sf_wjets)
  print('  '+str(wc3ihBupSize))
  print('  '+str(wc3ihBupSizePart))
  ####
  print('wcc 3 Iso')
  wcc3ihBup,wcc3ihBupSize,wcc3ihBupSizePart,wcc3ihBupEntries = h.gram(w3_tree,leaf,xmin,xmax,steps,cutMcWccIso_Bup,I,F)
  wcc3ihBup.SetName('wcc3ihBup')
  wcc3ihBup.Scale(sf_wjets)
  print('  '+str(wcc3ihBupSize))
  print('  '+str(wcc3ihBupSizePart))
  ####
  print('wbb 3 Iso')
  wbb3ihBup,wbb3ihBupSize,wbb3ihBupSizePart,wbb3ihBupEntries = h.gram(w3_tree,leaf,xmin,xmax,steps,cutMcWbbIso_Bup,I,F)
  wbb3ihBup.SetName('wbb3ihBup')
  wbb3ihBup.Scale(sf_wjets)
  print('  '+str(wbb3ihBupSize))
  print('  '+str(wbb3ihBupSizePart))
 #####
  print('wl 4 Iso')
  wl4ihBup,wl4ihBupSize,wl4ihBupSizePart,wl4ihBupEntries = h.gram(w4_tree,leaf,xmin,xmax,steps,cutMcWlIso_Bup,I,F)
  wl4ihBup.SetName('wl4ihBup')
  wl4ihBup.Scale(sf_wjets)
  print('  '+str(wl4ihBupSize))
  print('  '+str(wl4ihBupSizePart))
  ####
  print('wc 4 Iso')
  wc4ihBup,wc4ihBupSize,wc4ihBupSizePart,wc4ihBupEntries = h.gram(w4_tree,leaf,xmin,xmax,steps,cutMcWcIso_Bup,I,F)
  wc4ihBup.SetName('wc4ihBup')
  wc4ihBup.Scale(sf_wjets)
  print('  '+str(wc4ihBupSize))
  print('  '+str(wc4ihBupSizePart))
  ####
  print('wcc 4 Iso')
  wcc4ihBup,wcc4ihBupSize,wcc4ihBupSizePart,wcc4ihBupEntries = h.gram(w4_tree,leaf,xmin,xmax,steps,cutMcWccIso_Bup,I,F)
  wcc4ihBup.SetName('wcc4ihBup')
  wcc4ihBup.Scale(sf_wjets)
  print('  '+str(wcc4ihBupSize))
  print('  '+str(wcc4ihBupSizePart))
  ####
  print('wbb 4 Iso')
  wbb4ihBup,wbb4ihBupSize,wbb4ihBupSizePart,wbb4ihBupEntries = h.gram(w4_tree,leaf,xmin,xmax,steps,cutMcWbbIso_Bup,I,F)
  wbb4ihBup.SetName('wbb4ihBup')
  wbb4ihBup.Scale(sf_wjets)
  print('  '+str(wbb4ihBupSize))
  print('  '+str(wbb4ihBupSizePart))
  ### Wbb 4 Flavor
  print('wbb 4F Iso')
  wbb4fihBup,wbb4fihSizeBup,wbb4fihSizePartBup,wbb4fihEntriesBup = h.gram(w4f_tree,leaf,xmin,xmax,steps,cutMcWbbIso_Bup,I,F)
  wbb4fihBup.SetName('wbb4fihBup')
  wbb4fihBup.Scale(sf_wjets)
  print('  '+str(wbb4fihSizeBup))
  print('  '+str(wbb4fihSizePartBup))

 ## B Down 
 #### Drell
  print("z Iso")
  zihBdn,zihBdnSize,zihBdnSizePart,zihBdnEntries = h.gram(z_tree,leaf,xmin,xmax,steps,cutMcIso_Bdn,I,F)
  zihBdn.SetName('zihBdn')
  zihBdn.Scale(sf_drell)
  print('  '+str(zihBdnSize))
  print('  '+str(zihBdnSizePart))
 #### Diboson
  print("ww Iso")
  wwihBdn,wwihBdnSize,wwihBdnSizePart,wwihBdnEntries = h.gram(ww_tree,leaf,xmin,xmax,steps,cutMcIso_Bdn,I,F)
  wwihBdn.SetName('wwihBdn')
  wwihBdn.Scale(sf_vv)
  print('  '+str(wwihBdnSize))
  print('  '+str(wwihBdnSizePart))
  ###
  print("wz Iso")
  wzihBdn,wzihBdnSize,wzihBdnSizePart,wzihBdnEntries = h.gram(wz_tree,leaf,xmin,xmax,steps,cutMcIso_Bdn,I,F)
  wzihBdn.SetName('wzihBdn')
  wzihBdn.Scale(sf_vv)
  print('  '+str(wzihBdnSize))
  print('  '+str(wzihBdnSizePart))
  ###
  print("zz Iso")
  zzihBdn,zzihBdnSize,zzihBdnSizePart,zzihBdnEntries = h.gram(zz_tree,leaf,xmin,xmax,steps,cutMcIso_Bdn,I,F)
  zzihBdn.SetName('zzihBdn')
  zzihBdn.Scale(sf_vv)
  print('  '+str(zzihBdnSize))
  print('  '+str(zzihBdnSizePart))
 #### Single Top
  print('t t Iso')
  t_tihBdn,t_tihBdnSize,t_tihBdnSizePart,t_tihBdnEntries = h.gram(t_t_tree,leaf,xmin,xmax,steps,cutMcIso_Bdn,I,F)
  t_tihBdn.SetName('t_tihBdn')
  t_tihBdn.Scale(sf_st_t)
  print('  '+str(t_tihBdnSize))
  print('  '+str(t_tihBdnSizePart))
  ###
  print('tb t Iso')
  tb_tihBdn,tb_tihBdnSize,tb_tihBdnSizePart,tb_tihBdnEntries = h.gram(tb_t_tree,leaf,xmin,xmax,steps,cutMcIso_Bdn,I,F)
  tb_tihBdn.SetName('tb_tihBdn')
  tb_tihBdn.Scale(sf_st)
  print('  '+str(tb_tihBdnSize))
  print('  '+str(tb_tihBdnSizePart))
  ###
  print('t s Iso')
  t_sihBdn,t_sihBdnSize,t_sihBdnSizePart,t_sihBdnEntries = h.gram(t_s_tree,leaf,xmin,xmax,steps,cutMcIso_Bdn,I,F)
  t_sihBdn.SetName('t_sihBdn')
  t_sihBdn.Scale(sf_st)
  print('  '+str(t_sihBdnSize))
  print('  '+str(t_sihBdnSizePart))
  ###
  print('tb s Iso')
  tb_sihBdn,tb_sihBdnSize,tb_sihBdnSizePart,tb_sihBdnEntries = h.gram(tb_s_tree,leaf,xmin,xmax,steps,cutMcIso_Bdn,I,F)
  tb_sihBdn.SetName('tb_sihBdn')
  tb_sihBdn.Scale(sf_st)
  print('  '+str(tb_sihBdnSize))
  print('  '+str(tb_sihBdnSizePart))
  ###
  print('t tw Iso')
  t_twihBdn,t_twihBdnSize,t_twihBdnSizePart,t_twihBdnEntries = h.gram(t_tw_tree,leaf,xmin,xmax,steps,cutMcIso_Bdn,I,F)
  t_twihBdn.SetName('t_twihBdn')
  t_twihBdn.Scale(sf_st)
  print('  '+str(t_twihBdnSize))
  print('  '+str(t_twihBdnSizePart))
  ###
  print('tb tw Iso')
  tb_twihBdn,tb_twihBdnSize,tb_twihBdnSizePart,tb_twihBdnEntries = h.gram(tb_tw_tree,leaf,xmin,xmax,steps,cutMcIso_Bdn,I,F)
  tb_twihBdn.SetName('tb_twihBdn')
  tb_twihBdn.Scale(sf_st)
  print('  '+str(tb_twihBdnSize))
  print('  '+str(tb_twihBdnSizePart))
 #### TTbar
  print('ttb semi Iso')
  tt_semiihBdn,tt_semiihBdnSize,tt_semiihBdnSizePart,tt_semiihBdnEntries = h.gram(tt_semi_tree,leaf,xmin,xmax,steps,cutMcIso_Bdn,I,F)
  tt_semiihBdn.SetName('tt_semiihBdn')
  tt_semiihBdn.Scale(sf_ttbar)
  print('  '+str(tt_semiihBdnSize))
  print('  '+str(tt_semiihBdnSizePart))
  print('ttb full Iso')
  tt_fullihBdn,tt_fullihBdnSize,tt_fullihBdnSizePart,tt_fullihBdnEntries = h.gram(tt_full_tree,leaf,xmin,xmax,steps,cutMcIso_Bdn,I,F)
  tt_fullihBdn.SetName('tt_fullihBdn')
  tt_fullihBdn.Scale(sf_ttbar)
  print('  '+str(tt_fullihBdnSize))
  print('  '+str(tt_fullihBdnSizePart))
 
 #### W + Jets
  print('wl n Iso')
  wlnihBdn,wlnihBdnSize,wlnihBdnSizePart,wlnihBdnEntries = h.gram(wn_tree,leaf,xmin,xmax,steps,cutMcWlIso_Bdn,I,F)
  wlnihBdn.SetName('wlnihBdn')
  wlnihBdn.Scale(sf_wjets)
  print('  '+str(wlnihBdnSize))
  print('  '+str(wlnihBdnSizePart))
  ####
  print('wc n Iso')
  wcnihBdn,wcnihBdnSize,wcnihBdnSizePart,wcnihBdnEntries = h.gram(wn_tree,leaf,xmin,xmax,steps,cutMcWcIso_Bdn,I,F)
  wcnihBdn.SetName('wcnihBdn')
  wcnihBdn.Scale(sf_wjets)
  print('  '+str(wcnihBdnSize))
  print('  '+str(wcnihBdnSizePart))
  ####
  print('wcc n Iso')
  wccnihBdn,wccnihBdnSize,wccnihBdnSizePart,wccnihBdnEntries = h.gram(wn_tree,leaf,xmin,xmax,steps,cutMcWccIso_Bdn,I,F)
  wccnihBdn.SetName('wccnihBdn')
  wccnihBdn.Scale(sf_wjets)
  print('  '+str(wccnihBdnSize))
  print('  '+str(wccnihBdnSizePart))
  ####
  print('wbb n Iso')
  wbbnihBdn,wbbnihBdnSize,wbbnihBdnSizePart,wbbnihBdnEntries = h.gram(wn_tree,leaf,xmin,xmax,steps,cutMcWbbIso_Bdn,I,F)
  wbbnihBdn.SetName('wbbnihBdn')
  wbbnihBdn.Scale(sf_wjets)
  print('  '+str(wbbnihBdnSize))
  print('  '+str(wbbnihBdnSizePart))
 #####
  print('wl 1 Iso')
  wl1ihBdn,wl1ihBdnSize,wl1ihBdnSizePart,wl1ihBdnEntries = h.gram(w1_tree,leaf,xmin,xmax,steps,cutMcWlIso_Bdn,I,F)
  wl1ihBdn.SetName('wl1ihBdn')
  wl1ihBdn.Scale(sf_wjets)
  print('  '+str(wl1ihBdnSize))
  print('  '+str(wl1ihBdnSizePart))
  ####
  print('wc 1 Iso')
  wc1ihBdn,wc1ihBdnSize,wc1ihBdnSizePart,wc1ihBdnEntries = h.gram(w1_tree,leaf,xmin,xmax,steps,cutMcWcIso_Bdn,I,F)
  wc1ihBdn.SetName('wc1ihBdn')
  wc1ihBdn.Scale(sf_wjets)
  print('  '+str(wc1ihBdnSize))
  print('  '+str(wc1ihBdnSizePart))
  ####
  print('wcc 1 Iso')
  wcc1ihBdn,wcc1ihBdnSize,wcc1ihBdnSizePart,wcc1ihBdnEntries = h.gram(w1_tree,leaf,xmin,xmax,steps,cutMcWccIso_Bdn,I,F)
  wcc1ihBdn.SetName('wcc1ihBdn')
  wcc1ihBdn.Scale(sf_wjets)
  print('  '+str(wcc1ihBdnSize))
  print('  '+str(wcc1ihBdnSizePart))
  ####
  print('wbb 1 Iso')
  wbb1ihBdn,wbb1ihBdnSize,wbb1ihBdnSizePart,wbb1ihBdnEntries = h.gram(w1_tree,leaf,xmin,xmax,steps,cutMcWbbIso_Bdn,I,F)
  wbb1ihBdn.SetName('wbb1ihBdn')
  wbb1ihBdn.Scale(sf_wjets)
  print('  '+str(wbb1ihBdnSize))
  print('  '+str(wbb1ihBdnSizePart))
 #####
  print('wl 2 Iso')
  wl2ihBdn,wl2ihBdnSize,wl2ihBdnSizePart,wl2ihBdnEntries = h.gram(w2_tree,leaf,xmin,xmax,steps,cutMcWlIso_Bdn,I,F)
  wl2ihBdn.SetName('wl2ihBdn')
  wl2ihBdn.Scale(sf_wjets)
  print('  '+str(wl2ihBdnSize))
  print('  '+str(wl2ihBdnSizePart))
  ####
  print('wc 2 Iso')
  wc2ihBdn,wc2ihBdnSize,wc2ihBdnSizePart,wc2ihBdnEntries = h.gram(w2_tree,leaf,xmin,xmax,steps,cutMcWcIso_Bdn,I,F)
  wc2ihBdn.SetName('wc2ihBdn')
  wc2ihBdn.Scale(sf_wjets)
  print('  '+str(wc2ihBdnSize))
  print('  '+str(wc2ihBdnSizePart))
  ####
  print('wcc 2 Iso')
  wcc2ihBdn,wcc2ihBdnSize,wcc2ihBdnSizePart,wcc2ihBdnEntries = h.gram(w2_tree,leaf,xmin,xmax,steps,cutMcWccIso_Bdn,I,F)
  wcc2ihBdn.SetName('wcc2ihBdn')
  wcc2ihBdn.Scale(sf_wjets)
  print('  '+str(wcc2ihBdnSize))
  print('  '+str(wcc2ihBdnSizePart))
  ####
  print('wbb 2 Iso')
  wbb2ihBdn,wbb2ihBdnSize,wbb2ihBdnSizePart,wbb2ihBdnEntries = h.gram(w2_tree,leaf,xmin,xmax,steps,cutMcWbbIso_Bdn,I,F)
  wbb2ihBdn.SetName('wbb2ihBdn')
  wbb2ihBdn.Scale(sf_wjets)
  print('  '+str(wbb2ihBdnSize))
  print('  '+str(wbb2ihBdnSizePart))
 #####
  print('wl 3 Iso')
  wl3ihBdn,wl3ihBdnSize,wl3ihBdnSizePart,wl3ihBdnEntries = h.gram(w3_tree,leaf,xmin,xmax,steps,cutMcWlIso_Bdn,I,F)
  wl3ihBdn.SetName('wl3ihBdn')
  wl3ihBdn.Scale(sf_wjets)
  print('  '+str(wl3ihBdnSize))
  print('  '+str(wl3ihBdnSizePart))
  ####
  print('wc 3 Iso')
  wc3ihBdn,wc3ihBdnSize,wc3ihBdnSizePart,wc3ihBdnEntries = h.gram(w3_tree,leaf,xmin,xmax,steps,cutMcWcIso_Bdn,I,F)
  wc3ihBdn.SetName('wc3ihBdn')
  wc3ihBdn.Scale(sf_wjets)
  print('  '+str(wc3ihBdnSize))
  print('  '+str(wc3ihBdnSizePart))
  ####
  print('wcc 3 Iso')
  wcc3ihBdn,wcc3ihBdnSize,wcc3ihBdnSizePart,wcc3ihBdnEntries = h.gram(w3_tree,leaf,xmin,xmax,steps,cutMcWccIso_Bdn,I,F)
  wcc3ihBdn.SetName('wcc3ihBdn')
  wcc3ihBdn.Scale(sf_wjets)
  print('  '+str(wcc3ihBdnSize))
  print('  '+str(wcc3ihBdnSizePart))
  ####
  print('wbb 3 Iso')
  wbb3ihBdn,wbb3ihBdnSize,wbb3ihBdnSizePart,wbb3ihBdnEntries = h.gram(w3_tree,leaf,xmin,xmax,steps,cutMcWbbIso_Bdn,I,F)
  wbb3ihBdn.SetName('wbb3ihBdn')
  wbb3ihBdn.Scale(sf_wjets)
  print('  '+str(wbb3ihBdnSize))
  print('  '+str(wbb3ihBdnSizePart))
 #####
  print('wl 4 Iso')
  wl4ihBdn,wl4ihBdnSize,wl4ihBdnSizePart,wl4ihBdnEntries = h.gram(w4_tree,leaf,xmin,xmax,steps,cutMcWlIso_Bdn,I,F)
  wl4ihBdn.SetName('wl4ihBdn')
  wl4ihBdn.Scale(sf_wjets)
  print('  '+str(wl4ihBdnSize))
  print('  '+str(wl4ihBdnSizePart))
  ####
  print('wc 4 Iso')
  wc4ihBdn,wc4ihBdnSize,wc4ihBdnSizePart,wc4ihBdnEntries = h.gram(w4_tree,leaf,xmin,xmax,steps,cutMcWcIso_Bdn,I,F)
  wc4ihBdn.SetName('wc4ihBdn')
  wc4ihBdn.Scale(sf_wjets)
  print('  '+str(wc4ihBdnSize))
  print('  '+str(wc4ihBdnSizePart))
  ####
  print('wcc 4 Iso')
  wcc4ihBdn,wcc4ihBdnSize,wcc4ihBdnSizePart,wcc4ihBdnEntries = h.gram(w4_tree,leaf,xmin,xmax,steps,cutMcWccIso_Bdn,I,F)
  wcc4ihBdn.SetName('wcc4ihBdn')
  wcc4ihBdn.Scale(sf_wjets)
  print('  '+str(wcc4ihBdnSize))
  print('  '+str(wcc4ihBdnSizePart))
  ####
  print('wbb 4 Iso')
  wbb4ihBdn,wbb4ihBdnSize,wbb4ihBdnSizePart,wbb4ihBdnEntries = h.gram(w4_tree,leaf,xmin,xmax,steps,cutMcWbbIso_Bdn,I,F)
  wbb4ihBdn.SetName('wbb4ihBdn')
  wbb4ihBdn.Scale(sf_wjets)
  print('  '+str(wbb4ihBdnSize))
  print('  '+str(wbb4ihBdnSizePart))
  ### Wbb 4 Flavor
  print('wbb 4F Iso')
  wbb4fihBdn,wbb4fihSizeBdn,wbb4fihSizePartBdn,wbb4fihEntriesBdn = h.gram(w4f_tree,leaf,xmin,xmax,steps,cutMcWbbIso_Bdn,I,F)
  wbb4fihBdn.SetName('wbb4fihBdn')
  wbb4fihBdn.Scale(sf_wjets)
  print('  '+str(wbb4fihSizeBdn))
  print('  '+str(wbb4fihSizePartBdn))

#### Drell
 print("z Iso")
 zih,zihSize,zihSizePart,zihEntries = h.gram(z_tree,leaf,xmin,xmax,steps,CutsMCi,I,F)
 zih.SetName('zih')
 zih.Scale(sf_drell)
 print('  '+str(zihSize))
 print('  '+str(zihSizePart))
#### Diboson
 print("ww Iso")
 wwih,wwihSize,wwihSizePart,wwihEntries = h.gram(ww_tree,leaf,xmin,xmax,steps,CutsMCi,I,F)
 wwih.SetName('wwih')
 wwih.Scale(sf_vv)
 print('  '+str(wwihSize))
 print('  '+str(wwihSizePart))
 ###
 print("wz Iso")
 wzih,wzihSize,wzihSizePart,wzihEntries = h.gram(wz_tree,leaf,xmin,xmax,steps,CutsMCi,I,F)
 wzih.SetName('wzih')
 wzih.Scale(sf_vv)
 print('  '+str(wzihSize))
 print('  '+str(wzihSizePart))
 ###
 print("zz Iso")
 zzih,zzihSize,zzihSizePart,zzihEntries = h.gram(zz_tree,leaf,xmin,xmax,steps,CutsMCi,I,F)
 zzih.SetName('zzih')
 zzih.Scale(sf_vv)
 print('  '+str(zzihSize))
 print('  '+str(zzihSizePart))
#### Single Top
 print('t t Iso')
 t_tih,t_tihSize,t_tihSizePart,t_tihEntries = h.gram(t_t_tree,leaf,xmin,xmax,steps,CutsMCi,I,F)
 t_tih.SetName('t_tih')
 t_tih.Scale(sf_st_t)
 print('  '+str(t_tihSize))
 print('  '+str(t_tihSizePart))
 ###
 print('tb t Iso')
 tb_tih,tb_tihSize,tb_tihSizePart,tb_tihEntries = h.gram(tb_t_tree,leaf,xmin,xmax,steps,CutsMCi,I,F)
 tb_tih.SetName('tb_tih')
 tb_tih.Scale(sf_st)
 print('  '+str(tb_tihSize))
 print('  '+str(tb_tihSizePart))
 ###
 print('t s Iso')
 t_sih,t_sihSize,t_sihSizePart,t_sihEntries = h.gram(t_s_tree,leaf,xmin,xmax,steps,CutsMCi,I,F)
 t_sih.SetName('t_sih')
 t_sih.Scale(sf_st)
 print('  '+str(t_sihSize))
 print('  '+str(t_sihSizePart))
 ###
 print('tb s Iso')
 tb_sih,tb_sihSize,tb_sihSizePart,tb_sihEntries = h.gram(tb_s_tree,leaf,xmin,xmax,steps,CutsMCi,I,F)
 tb_sih.SetName('tb_sih')
 tb_sih.Scale(sf_st)
 print('  '+str(tb_sihSize))
 print('  '+str(tb_sihSizePart))
 ###
 print('t tw Iso')
 t_twih,t_twihSize,t_twihSizePart,t_twihEntries = h.gram(t_tw_tree,leaf,xmin,xmax,steps,CutsMCi,I,F)
 t_twih.SetName('t_twih')
 t_twih.Scale(sf_st)
 print('  '+str(t_twihSize))
 print('  '+str(t_twihSizePart))
 ###
 print('tb tw Iso')
 tb_twih,tb_twihSize,tb_twihSizePart,tb_twihEntries = h.gram(tb_tw_tree,leaf,xmin,xmax,steps,CutsMCi,I,F)
 tb_twih.SetName('tb_twih')
 tb_twih.Scale(sf_st)
 print('  '+str(tb_twihSize))
 print('  '+str(tb_twihSizePart))
#### TTbar
 print('ttb semi Iso')
 tt_semiih,tt_semiihSize,tt_semiihSizePart,tt_semiihEntries = h.gram(tt_semi_tree,leaf,xmin,xmax,steps,CutsMCiT,I,F)
 tt_semiih.SetName('tt_semiih')
 tt_semiih.Scale(sf_ttbar)
 print('  '+str(tt_semiihSize))
 print('  '+str(tt_semiihSizePart))
 print('ttb full Iso')
 tt_fullih,tt_fullihSize,tt_fullihSizePart,tt_fullihEntries = h.gram(tt_full_tree,leaf,xmin,xmax,steps,CutsMCiT,I,F)
 tt_fullih.SetName('tt_fullih')
 tt_fullih.Scale(sf_ttbar)
 print('  '+str(tt_fullihSize))
 print('  '+str(tt_fullihSizePart))
 if eventTreeLocation ==  'muNuEventTree/eventTree' :
  print('ttb semi Iso Up')
  tt_semiihUp,tt_semiihSizeUp,tt_semiihSizePartUp,tt_semiihEntriesUp = h.gram(tt_semi_tree,leaf,xmin,xmax,steps,CutsMCiTup,I,F)
  tt_semiihUp.SetName('tt_semiihUp')
  tt_semiihUp.Scale(sf_ttbar)
  print('  '+str(tt_semiihSizeUp))
  print('  '+str(tt_semiihSizePartUp))
  print('ttb full Iso Up')
  tt_fullihUp,tt_fullihSizeUp,tt_fullihSizePartUp,tt_fullihEntriesUp = h.gram(tt_full_tree,leaf,xmin,xmax,steps,CutsMCiTup,I,F)
  tt_fullihUp.SetName('tt_fullihUp')
  tt_fullihUp.Scale(sf_ttbar)
  print('  '+str(tt_fullihSizeUp))
  print('  '+str(tt_fullihSizePartUp))
  print('ttb semi Iso Dn')
  tt_semiihDn,tt_semiihSizeDn,tt_semiihSizePartDn,tt_semiihEntriesDn = h.gram(tt_semi_tree,leaf,xmin,xmax,steps,CutsMCiTdn,I,F)
  tt_semiihDn.SetName('tt_semiihDn')
  tt_semiihDn.Scale(sf_ttbar)
  print('  '+str(tt_semiihSizeDn))
  print('  '+str(tt_semiihSizePartDn))
  print('ttb full Iso Dn')
  tt_fullihDn,tt_fullihSizeDn,tt_fullihSizePartDn,tt_fullihEntriesDn = h.gram(tt_full_tree,leaf,xmin,xmax,steps,CutsMCiTdn,I,F)
  tt_fullihDn.SetName('tt_fullihDn')
  tt_fullihDn.Scale(sf_ttbar)
  print('  '+str(tt_fullihSizeDn))
  print('  '+str(tt_fullihSizePartDn))

#### W + Jets
 print('wl n Iso')
 wlnih,wlnihSize,wlnihSizePart,wlnihEntries = h.gram(wn_tree,leaf,xmin,xmax,steps,CutsMCiwl,I,F)
 wlnih.SetName('wlnih')
 wlnih.Scale(sf_wjets)
 print('  '+str(wlnihSize))
 print('  '+str(wlnihSizePart))
 ####
 print('wc n Iso')
 wcnih,wcnihSize,wcnihSizePart,wcnihEntries = h.gram(wn_tree,leaf,xmin,xmax,steps,CutsMCiwc,I,F)
 wcnih.SetName('wcnih')
 wcnih.Scale(sf_wjets)
 print('  '+str(wcnihSize))
 print('  '+str(wcnihSizePart))
 ####
 print('wcc n Iso')
 wccnih,wccnihSize,wccnihSizePart,wccnihEntries = h.gram(wn_tree,leaf,xmin,xmax,steps,CutsMCiwcc,I,F)
 wccnih.SetName('wccnih')
 wccnih.Scale(sf_wjets)
 print('  '+str(wccnihSize))
 print('  '+str(wccnihSizePart))
 ####
 print('wbb n Iso')
 wbbnih,wbbnihSize,wbbnihSizePart,wbbnihEntries = h.gram(wn_tree,leaf,xmin,xmax,steps,CutsMCiwbb,I,F)
 wbbnih.SetName('wbbnih')
 wbbnih.Scale(sf_wjets)
 print('  '+str(wbbnihSize))
 print('  '+str(wbbnihSizePart))
#####
 print('wl 1 Iso')
 wl1ih,wl1ihSize,wl1ihSizePart,wl1ihEntries = h.gram(w1_tree,leaf,xmin,xmax,steps,CutsMCiwl,I,F)
 wl1ih.SetName('wl1ih')
 wl1ih.Scale(sf_wjets)
 print('  '+str(wl1ihSize))
 print('  '+str(wl1ihSizePart))
 ####
 print('wc 1 Iso')
 wc1ih,wc1ihSize,wc1ihSizePart,wc1ihEntries = h.gram(w1_tree,leaf,xmin,xmax,steps,CutsMCiwc,I,F)
 wc1ih.SetName('wc1ih')
 wc1ih.Scale(sf_wjets)
 print('  '+str(wc1ihSize))
 print('  '+str(wc1ihSizePart))
 ####
 print('wcc 1 Iso')
 wcc1ih,wcc1ihSize,wcc1ihSizePart,wcc1ihEntries = h.gram(w1_tree,leaf,xmin,xmax,steps,CutsMCiwcc,I,F)
 wcc1ih.SetName('wcc1ih')
 wcc1ih.Scale(sf_wjets)
 print('  '+str(wcc1ihSize))
 print('  '+str(wcc1ihSizePart))
 ####
 print('wbb 1 Iso')
 wbb1ih,wbb1ihSize,wbb1ihSizePart,wbb1ihEntries = h.gram(w1_tree,leaf,xmin,xmax,steps,CutsMCiwbb,I,F)
 wbb1ih.SetName('wbb1ih')
 wbb1ih.Scale(sf_wjets)
 print('  '+str(wbb1ihSize))
 print('  '+str(wbb1ihSizePart))
#####
 print('wl 2 Iso')
 wl2ih,wl2ihSize,wl2ihSizePart,wl2ihEntries = h.gram(w2_tree,leaf,xmin,xmax,steps,CutsMCiwl,I,F)
 wl2ih.SetName('wl2ih')
 wl2ih.Scale(sf_wjets)
 print('  '+str(wl2ihSize))
 print('  '+str(wl2ihSizePart))
 ####
 print('wc 2 Iso')
 wc2ih,wc2ihSize,wc2ihSizePart,wc2ihEntries = h.gram(w2_tree,leaf,xmin,xmax,steps,CutsMCiwc,I,F)
 wc2ih.SetName('wc2ih')
 wc2ih.Scale(sf_wjets)
 print('  '+str(wc2ihSize))
 print('  '+str(wc2ihSizePart))
 ####
 print('wcc 2 Iso')
 wcc2ih,wcc2ihSize,wcc2ihSizePart,wcc2ihEntries = h.gram(w2_tree,leaf,xmin,xmax,steps,CutsMCiwcc,I,F)
 wcc2ih.SetName('wcc2ih')
 wcc2ih.Scale(sf_wjets)
 print('  '+str(wcc2ihSize))
 print('  '+str(wcc2ihSizePart))
 ####
 print('wbb 2 Iso')
 wbb2ih,wbb2ihSize,wbb2ihSizePart,wbb2ihEntries = h.gram(w2_tree,leaf,xmin,xmax,steps,CutsMCiwbb,I,F)
 wbb2ih.SetName('wbb2ih')
 wbb2ih.Scale(sf_wjets)
 print('  '+str(wbb2ihSize))
 print('  '+str(wbb2ihSizePart))
#####
 print('wl 3 Iso')
 wl3ih,wl3ihSize,wl3ihSizePart,wl3ihEntries = h.gram(w3_tree,leaf,xmin,xmax,steps,CutsMCiwl,I,F)
 wl3ih.SetName('wl3ih')
 wl3ih.Scale(sf_wjets)
 print('  '+str(wl3ihSize))
 print('  '+str(wl3ihSizePart))
 ####
 print('wc 3 Iso')
 wc3ih,wc3ihSize,wc3ihSizePart,wc3ihEntries = h.gram(w3_tree,leaf,xmin,xmax,steps,CutsMCiwc,I,F)
 wc3ih.SetName('wc3ih')
 wc3ih.Scale(sf_wjets)
 print('  '+str(wc3ihSize))
 print('  '+str(wc3ihSizePart))
 ####
 print('wcc 3 Iso')
 wcc3ih,wcc3ihSize,wcc3ihSizePart,wcc3ihEntries = h.gram(w3_tree,leaf,xmin,xmax,steps,CutsMCiwcc,I,F)
 wcc3ih.SetName('wcc3ih')
 wcc3ih.Scale(sf_wjets)
 print('  '+str(wcc3ihSize))
 print('  '+str(wcc3ihSizePart))
 ####
 print('wbb 3 Iso')
 wbb3ih,wbb3ihSize,wbb3ihSizePart,wbb3ihEntries = h.gram(w3_tree,leaf,xmin,xmax,steps,CutsMCiwbb,I,F)
 wbb3ih.SetName('wbb3ih')
 wbb3ih.Scale(sf_wjets)
 print('  '+str(wbb3ihSize))
 print('  '+str(wbb3ihSizePart))
#####
 print('wl 4 Iso')
 wl4ih,wl4ihSize,wl4ihSizePart,wl4ihEntries = h.gram(w4_tree,leaf,xmin,xmax,steps,CutsMCiwl,I,F)
 wl4ih.SetName('wl4ih')
 wl4ih.Scale(sf_wjets)
 print('  '+str(wl4ihSize))
 print('  '+str(wl4ihSizePart))
 ####
 print('wc 4 Iso')
 wc4ih,wc4ihSize,wc4ihSizePart,wc4ihEntries = h.gram(w4_tree,leaf,xmin,xmax,steps,CutsMCiwc,I,F)
 wc4ih.SetName('wc4ih')
 wc4ih.Scale(sf_wjets)
 print('  '+str(wc4ihSize))
 print('  '+str(wc4ihSizePart))
 ####
 print('wcc 4 Iso')
 wcc4ih,wcc4ihSize,wcc4ihSizePart,wcc4ihEntries = h.gram(w4_tree,leaf,xmin,xmax,steps,CutsMCiwcc,I,F)
 wcc4ih.SetName('wcc4ih')
 wcc4ih.Scale(sf_wjets)
 print('  '+str(wcc4ihSize))
 print('  '+str(wcc4ihSizePart))
 ####
 print('wbb 4 Iso')
 wbb4ih,wbb4ihSize,wbb4ihSizePart,wbb4ihEntries = h.gram(w4_tree,leaf,xmin,xmax,steps,CutsMCiwbb,I,F)
 wbb4ih.SetName('wbb4ih')
 wbb4ih.Scale(sf_wjets)
 print('  '+str(wbb4ihSize))
 print('  '+str(wbb4ihSizePart))
 ####
 print('wbb 4F Iso')
 wbb4fih,wbb4fihSize,wbb4fihSizePart,wbb4fihEntries = h.gram(w4f_tree,leaf,xmin,xmax,steps,CutsMCiwbb,I,F)
 wbb4fih.SetName('wbb4fih')
 wbb4fih.Scale(sf_wjets)
 print('  '+str(wbb4fihSize))
 print('  '+str(wbb4fihSizePart))
 
 if eventTreeLocation == 'muNuEventTree/eventTree' :
  data_obs = dataih.Clone()
  data_obs.SetName("data_obs")

  QCD     = qh.Clone()
  QCD.SetName("QCD")
  DY     = zih.Clone()
  DY.SetName("DY")
  VV    = wwih.Clone()
  VV.SetName("VV")
  VV.Add(wzih)
  VV.Add(zzih)
  T     = t_tih.Clone()
  T.SetName("T")
  T.Add(t_sih)
  T.Add(t_twih)
  Tbar    = tb_tih.Clone()
  Tbar.SetName("Tbar")
  Tbar.Add(tb_sih)
  Tbar.Add(tb_twih)
  TTbar   = tt_semiih.Clone()
  TTbar.SetName("TTbar")
  TTbar.Add(tt_fullih)
  Wl    = wlnih.Clone()
  Wl.SetName("Wl")
  Wl.Add(wl1ih)
  Wl.Add(wl2ih)
  Wl.Add(wl3ih)
  Wl.Add(wl4ih)
  Wl.Add(wcnih)
  Wl.Add(wc1ih)
  Wl.Add(wc2ih)
  Wl.Add(wc3ih)
  Wl.Add(wc4ih)
  Wcc    = wccnih.Clone()
  Wcc.SetName("Wcc")
  Wcc.Add(wcc1ih)
  Wcc.Add(wcc2ih)
  Wcc.Add(wcc3ih)
  Wcc.Add(wcc4ih)
  Wbb5F   = wbbnih.Clone()
  Wbb5F.SetName("Wbb5F")
  Wbb5F.Add(wbb1ih)
  Wbb5F.Add(wbb2ih)
  Wbb5F.Add(wbb3ih)
  Wbb5F.Add(wbb4ih)
  Wbb4F = wbb4fih.Clone()
  Wbb4F.SetName("Wbb4F")
 
  DY_BeffUp     = zihBup.Clone()
  DY_BeffUp.SetName("DY_BeffUp")
  VV_BeffUp    = wwihBup.Clone()
  VV_BeffUp.SetName("VV_BeffUp")
  VV_BeffUp.Add(wzihBup)
  VV_BeffUp.Add(zzihBup)
  T_BeffUp     = t_tihBup.Clone()
  T_BeffUp.SetName("T_BeffUp")
  T_BeffUp.Add(t_sihBup)
  T_BeffUp.Add(t_twihBup)
  Tbar_BeffUp    = tb_tihBup.Clone()
  Tbar_BeffUp.SetName("Tbar_BeffUp")
  Tbar_BeffUp.Add(tb_sihBup)
  Tbar_BeffUp.Add(tb_twihBup)
  TTbar_BeffUp   = tt_semiihBup.Clone()
  TTbar_BeffUp.SetName("TTbar_BeffUp")
  TTbar_BeffUp.Add(tt_fullihBup)
  Wl_BeffUp    = wlnihBup.Clone()
  Wl_BeffUp.SetName("Wl_BeffUp")
  Wl_BeffUp.Add(wl1ihBup)
  Wl_BeffUp.Add(wl2ihBup)
  Wl_BeffUp.Add(wl3ihBup)
  Wl_BeffUp.Add(wl4ihBup)
  Wl_BeffUp.Add(wcnihBup)
  Wl_BeffUp.Add(wc1ihBup)
  Wl_BeffUp.Add(wc2ihBup)
  Wl_BeffUp.Add(wc3ihBup)
  Wl_BeffUp.Add(wc4ihBup)
  Wcc_BeffUp    = wccnihBup.Clone()
  Wcc_BeffUp.SetName("Wcc_BeffUp")
  Wcc_BeffUp.Add(wcc1ihBup)
  Wcc_BeffUp.Add(wcc2ihBup)
  Wcc_BeffUp.Add(wcc3ihBup)
  Wcc_BeffUp.Add(wcc4ihBup)
  Wbb5F_BeffUp   = wbbnihBup.Clone()
  Wbb5F_BeffUp.SetName("Wbb5F_BeffUp")
  Wbb5F_BeffUp.Add(wbb1ihBup)
  Wbb5F_BeffUp.Add(wbb2ihBup)
  Wbb5F_BeffUp.Add(wbb3ihBup)
  Wbb5F_BeffUp.Add(wbb4ihBup)
  Wbb4F_BeffUp = wbb4fihBup.Clone()
  Wbb4F_BeffUp.SetName("Wbb4F_BeffUp")
 
  DY_BeffDown     = zihBdn.Clone()
  DY_BeffDown.SetName("DY_BeffDown")
  VV_BeffDown    = wwihBdn.Clone()
  VV_BeffDown.SetName("VV_BeffDown")
  VV_BeffDown.Add(wzihBdn)
  VV_BeffDown.Add(zzihBdn)
  T_BeffDown     = t_tihBdn.Clone()
  T_BeffDown.SetName("T_BeffDown")
  T_BeffDown.Add(t_sihBdn)
  T_BeffDown.Add(t_twihBdn)
  Tbar_BeffDown    = tb_tihBdn.Clone()
  Tbar_BeffDown.SetName("Tbar_BeffDown")
  Tbar_BeffDown.Add(tb_sihBdn)
  Tbar_BeffDown.Add(tb_twihBdn)
  TTbar_BeffDown   = tt_semiihBdn.Clone()
  TTbar_BeffDown.SetName("TTbar_BeffDown")
  TTbar_BeffDown.Add(tt_fullihBdn)
  Wl_BeffDown    = wlnihBdn.Clone()
  Wl_BeffDown.SetName("Wl_BeffDown")
  Wl_BeffDown.Add(wl1ihBdn)
  Wl_BeffDown.Add(wl2ihBdn)
  Wl_BeffDown.Add(wl3ihBdn)
  Wl_BeffDown.Add(wl4ihBdn)
  Wl_BeffDown.Add(wcnihBdn)
  Wl_BeffDown.Add(wc1ihBdn)
  Wl_BeffDown.Add(wc2ihBdn)
  Wl_BeffDown.Add(wc3ihBdn)
  Wl_BeffDown.Add(wc4ihBdn)
  Wcc_BeffDown    = wccnihBdn.Clone()
  Wcc_BeffDown.SetName("Wcc_BeffDown")
  Wcc_BeffDown.Add(wcc1ihBdn)
  Wcc_BeffDown.Add(wcc2ihBdn)
  Wcc_BeffDown.Add(wcc3ihBdn)
  Wcc_BeffDown.Add(wcc4ihBdn)
  Wbb5F_BeffDown   = wbbnihBdn.Clone()
  Wbb5F_BeffDown.SetName("Wbb5F_BeffDown")
  Wbb5F_BeffDown.Add(wbb1ihBdn)
  Wbb5F_BeffDown.Add(wbb2ihBdn)
  Wbb5F_BeffDown.Add(wbb3ihBdn)
  Wbb5F_BeffDown.Add(wbb4ihBdn)
  Wbb4F_BeffDown = wbb4fihBdn.Clone()
  Wbb4F_BeffDown.SetName("Wbb4F_BeffDown")
 
#  # qcd already taken care of
#  zihTup    = zihNo.Clone()
#  zihTup.SetName("zihTup")
#  vvihTup   = vvihNo.Clone()
#  vvihTup.SetName("vvihTup")
#  tihTup    = tihNo.Clone()
#  tihTup.SetName("tihTup")
#  tbihTup   = tbihNo.Clone()
#  tbihTup.SetName("tbihTup")
#  t_twihTup = t_twihNo.Clone()
#  t_twihTup.SetName("t_twihTup")
#  ttbihTup  = tt_fullihUp.Clone()
#  ttbihTup.SetName("ttbihTup")
#  ttbihTup.Add(tt_semiihUp)
#  wlihTup   = wlihNo.Clone()
#  wlihTup.SetName("wlihTup")
#  wcihTup   = wcihNo.Clone()
#  wcihTup.SetName("wcihTup")
#  wccihTup  = wccihNo.Clone()
#  wccihTup.SetName("wccihTup")
#  wbbihTup  = wbbihNo.Clone()
#  wbbihTup.SetName("wbbihTup")
#
#  # qcd already taken care of
#  zihTdn    = zihNo.Clone()
#  zihTdn.SetName("zihTdn")
#  vvihTdn   = vvihNo.Clone()
#  vvihTdn.SetName("vvihTdn")
#  tihTdn    = tihNo.Clone()
#  tihTdn.SetName("tihTdn")
#  tbihTdn   = tbihNo.Clone()
#  tbihTdn.SetName("tbihTdn")
#  t_twihTdn = t_twihNo.Clone()
#  t_twihTdn.SetName("t_twihTdn")
#  ttbihTdn  = tt_fullihUp.Clone()
#  ttbihTdn.SetName("ttbihTdn")
#  ttbihTdn.Add(tt_semiihUp)
#  wlihTdn   = wlihNo.Clone()
#  wlihTdn.SetName("wlihTdn")
#  wcihTdn   = wcihNo.Clone()
#  wcihTdn.SetName("wcihTdn")
#  wccihTdn  = wccihNo.Clone()
#  wccihTdn.SetName("wccihTdn")
#  wbbihTdn  = wbbihNo.Clone()
#  wbbihTdn.SetName("wbbihTdn")

 if eventTreeLocation == 'muNuEventTreeMuonUp/eventTree' :
  QCD_muonUp     = qh.Clone()
  QCD_muonUp.SetName("QCD_muonUp")
  DY_muonUp     = zih.Clone()
  DY_muonUp.SetName("DY_muonUp")
  VV_muonUp    = wwih.Clone()
  VV_muonUp.SetName("VV_muonUp")
  VV_muonUp.Add(wzih)
  VV_muonUp.Add(zzih)
  T_muonUp     = t_tih.Clone()
  T_muonUp.SetName("T_muonUp")
  T_muonUp.Add(t_sih)
  T_muonUp.Add(t_twih)
  Tbar_muonUp    = tb_tih.Clone()
  Tbar_muonUp.SetName("Tbar_muonUp")
  Tbar_muonUp.Add(tb_sih)
  Tbar_muonUp.Add(tb_twih)
  TTbar_muonUp   = tt_semiih.Clone()
  TTbar_muonUp.SetName("TTbar_muonUp")
  TTbar_muonUp.Add(tt_fullih)
  Wl_muonUp    = wlnih.Clone()
  Wl_muonUp.SetName("Wl_muonUp")
  Wl_muonUp.Add(wl1ih)
  Wl_muonUp.Add(wl2ih)
  Wl_muonUp.Add(wl3ih)
  Wl_muonUp.Add(wl4ih)
  Wl_muonUp.Add(wcnih)
  Wl_muonUp.Add(wc1ih)
  Wl_muonUp.Add(wc2ih)
  Wl_muonUp.Add(wc3ih)
  Wl_muonUp.Add(wc4ih)
  Wcc_muonUp    = wccnih.Clone()
  Wcc_muonUp.SetName("Wcc_muonUp")
  Wcc_muonUp.Add(wcc1ih)
  Wcc_muonUp.Add(wcc2ih)
  Wcc_muonUp.Add(wcc3ih)
  Wcc_muonUp.Add(wcc4ih)
  Wbb5F_muonUp   = wbbnih.Clone()
  Wbb5F_muonUp.SetName("Wbb5F_muonUp")
  Wbb5F_muonUp.Add(wbb1ih)
  Wbb5F_muonUp.Add(wbb2ih)
  Wbb5F_muonUp.Add(wbb3ih)
  Wbb5F_muonUp.Add(wbb4ih)
  Wbb4F_muonUp = wbb4fih.Clone()
  Wbb4F_muonUp.SetName("Wbb4F_muonUp")

 if eventTreeLocation == 'muNuEventTreeMuonDown/eventTree' : 
  QCD_muonDown     = qh.Clone()
  QCD_muonDown.SetName("QCD_muonDown")
  DY_muonDown     = zih.Clone()
  DY_muonDown.SetName("DY_muonDown")
  VV_muonDown    = wwih.Clone()
  VV_muonDown.SetName("VV_muonDown")
  VV_muonDown.Add(wzih)
  VV_muonDown.Add(zzih)
  T_muonDown     = t_tih.Clone()
  T_muonDown.SetName("T_muonDown")
  T_muonDown.Add(t_sih)
  T_muonDown.Add(t_twih)
  Tbar_muonDown    = tb_tih.Clone()
  Tbar_muonDown.SetName("Tbar_muonDown")
  Tbar_muonDown.Add(tb_sih)
  Tbar_muonDown.Add(tb_twih)
  TTbar_muonDown   = tt_semiih.Clone()
  TTbar_muonDown.SetName("TTbar_muonDown")
  TTbar_muonDown.Add(tt_fullih)
  Wl_muonDown    = wlnih.Clone()
  Wl_muonDown.SetName("Wl_muonDown")
  Wl_muonDown.Add(wl1ih)
  Wl_muonDown.Add(wl2ih)
  Wl_muonDown.Add(wl3ih)
  Wl_muonDown.Add(wl4ih)
  Wl_muonDown.Add(wcnih)
  Wl_muonDown.Add(wc1ih)
  Wl_muonDown.Add(wc2ih)
  Wl_muonDown.Add(wc3ih)
  Wl_muonDown.Add(wc4ih)
  Wcc_muonDown    = wccnih.Clone()
  Wcc_muonDown.SetName("Wcc_muonDown")
  Wcc_muonDown.Add(wcc1ih)
  Wcc_muonDown.Add(wcc2ih)
  Wcc_muonDown.Add(wcc3ih)
  Wcc_muonDown.Add(wcc4ih)
  Wbb5F_muonDown   = wbbnih.Clone()
  Wbb5F_muonDown.SetName("Wbb5F_muonDown")
  Wbb5F_muonDown.Add(wbb1ih)
  Wbb5F_muonDown.Add(wbb2ih)
  Wbb5F_muonDown.Add(wbb3ih)
  Wbb5F_muonDown.Add(wbb4ih)
  Wbb4F_muonDown = wbb4fih.Clone()
  Wbb4F_muonDown.SetName("Wbb4F_muonDown")

 if eventTreeLocation == 'muNuEventTreeJetUp/eventTree' : 
  QCD_jetUp     = qh.Clone()
  QCD_jetUp.SetName("QCD_jetUp")
  DY_jetUp     = zih.Clone()
  DY_jetUp.SetName("DY_jetUp")
  VV_jetUp    = wwih.Clone()
  VV_jetUp.SetName("VV_jetUp")
  VV_jetUp.Add(wzih)
  VV_jetUp.Add(zzih)
  T_jetUp     = t_tih.Clone()
  T_jetUp.SetName("T_jetUp")
  T_jetUp.Add(t_sih)
  T_jetUp.Add(t_twih)
  Tbar_jetUp    = tb_tih.Clone()
  Tbar_jetUp.SetName("Tbar_jetUp")
  Tbar_jetUp.Add(tb_sih)
  Tbar_jetUp.Add(tb_twih)
  TTbar_jetUp   = tt_semiih.Clone()
  TTbar_jetUp.SetName("TTbar_jetUp")
  TTbar_jetUp.Add(tt_fullih)
  Wl_jetUp    = wlnih.Clone()
  Wl_jetUp.SetName("Wl_jetUp")
  Wl_jetUp.Add(wl1ih)
  Wl_jetUp.Add(wl2ih)
  Wl_jetUp.Add(wl3ih)
  Wl_jetUp.Add(wl4ih)
  Wl_jetUp.Add(wcnih)
  Wl_jetUp.Add(wc1ih)
  Wl_jetUp.Add(wc2ih)
  Wl_jetUp.Add(wc3ih)
  Wl_jetUp.Add(wc4ih)
  Wcc_jetUp    = wccnih.Clone()
  Wcc_jetUp.SetName("Wcc_jetUp")
  Wcc_jetUp.Add(wcc1ih)
  Wcc_jetUp.Add(wcc2ih)
  Wcc_jetUp.Add(wcc3ih)
  Wcc_jetUp.Add(wcc4ih)
  Wbb5F_jetUp   = wbbnih.Clone()
  Wbb5F_jetUp.SetName("Wbb5F_jetUp")
  Wbb5F_jetUp.Add(wbb1ih)
  Wbb5F_jetUp.Add(wbb2ih)
  Wbb5F_jetUp.Add(wbb3ih)
  Wbb5F_jetUp.Add(wbb4ih)
  Wbb4F_jetUp = wbb4fih.Clone()
  Wbb4F_jetUp.SetName("Wbb4F_jetUp")

 if eventTreeLocation == 'muNuEventTreeJetDown/eventTree' : 
  QCD_jetDown     = qh.Clone()
  QCD_jetDown.SetName("QCD_jetDown")
  DY_jetDown     = zih.Clone()
  DY_jetDown.SetName("DY_jetDown")
  VV_jetDown    = wwih.Clone()
  VV_jetDown.SetName("VV_jetDown")
  VV_jetDown.Add(wzih)
  VV_jetDown.Add(zzih)
  T_jetDown     = t_tih.Clone()
  T_jetDown.SetName("T_jetDown")
  T_jetDown.Add(t_sih)
  T_jetDown.Add(t_twih)
  Tbar_jetDown    = tb_tih.Clone()
  Tbar_jetDown.SetName("Tbar_jetDown")
  Tbar_jetDown.Add(tb_sih)
  Tbar_jetDown.Add(tb_twih)
  TTbar_jetDown   = tt_semiih.Clone()
  TTbar_jetDown.SetName("TTbar_jetDown")
  TTbar_jetDown.Add(tt_fullih)
  Wl_jetDown    = wlnih.Clone()
  Wl_jetDown.SetName("Wl_jetDown")
  Wl_jetDown.Add(wl1ih)
  Wl_jetDown.Add(wl2ih)
  Wl_jetDown.Add(wl3ih)
  Wl_jetDown.Add(wl4ih)
  Wl_jetDown.Add(wcnih)
  Wl_jetDown.Add(wc1ih)
  Wl_jetDown.Add(wc2ih)
  Wl_jetDown.Add(wc3ih)
  Wl_jetDown.Add(wc4ih)
  Wcc_jetDown    = wccnih.Clone()
  Wcc_jetDown.SetName("Wcc_jetDown")
  Wcc_jetDown.Add(wcc1ih)
  Wcc_jetDown.Add(wcc2ih)
  Wcc_jetDown.Add(wcc3ih)
  Wcc_jetDown.Add(wcc4ih)
  Wbb5F_jetDown   = wbbnih.Clone()
  Wbb5F_jetDown.SetName("Wbb5F_jetDown")
  Wbb5F_jetDown.Add(wbb1ih)
  Wbb5F_jetDown.Add(wbb2ih)
  Wbb5F_jetDown.Add(wbb3ih)
  Wbb5F_jetDown.Add(wbb4ih)
  Wbb4F_jetDown = wbb4fih.Clone()
  Wbb4F_jetDown.SetName("Wbb4F_jetDown")

 if eventTreeLocation == 'muNuEventTreeUCEUp/eventTree':
  QCD_uceUp     = qh.Clone()
  QCD_uceUp.SetName("QCD_uceUp")
  DY_uceUp     = zih.Clone()
  DY_uceUp.SetName("DY_uceUp")
  VV_uceUp    = wwih.Clone()
  VV_uceUp.SetName("VV_uceUp")
  VV_uceUp.Add(wzih)
  VV_uceUp.Add(zzih)
  T_uceUp     = t_tih.Clone()
  T_uceUp.SetName("T_uceUp")
  T_uceUp.Add(t_sih)
  T_uceUp.Add(t_twih)
  Tbar_uceUp    = tb_tih.Clone()
  Tbar_uceUp.SetName("Tbar_uceUp")
  Tbar_uceUp.Add(tb_sih)
  Tbar_uceUp.Add(tb_twih)
  TTbar_uceUp   = tt_semiih.Clone()
  TTbar_uceUp.SetName("TTbar_uceUp")
  TTbar_uceUp.Add(tt_fullih)
  Wl_uceUp    = wlnih.Clone()
  Wl_uceUp.SetName("Wl_uceUp")
  Wl_uceUp.Add(wl1ih)
  Wl_uceUp.Add(wl2ih)
  Wl_uceUp.Add(wl3ih)
  Wl_uceUp.Add(wl4ih)
  Wl_uceUp.Add(wcnih)
  Wl_uceUp.Add(wc1ih)
  Wl_uceUp.Add(wc2ih)
  Wl_uceUp.Add(wc3ih)
  Wl_uceUp.Add(wc4ih)
  Wcc_uceUp    = wccnih.Clone()
  Wcc_uceUp.SetName("Wcc_uceUp")
  Wcc_uceUp.Add(wcc1ih)
  Wcc_uceUp.Add(wcc2ih)
  Wcc_uceUp.Add(wcc3ih)
  Wcc_uceUp.Add(wcc4ih)
  Wbb5F_uceUp   = wbbnih.Clone()
  Wbb5F_uceUp.SetName("Wbb5F_uceUp")
  Wbb5F_uceUp.Add(wbb1ih)
  Wbb5F_uceUp.Add(wbb2ih)
  Wbb5F_uceUp.Add(wbb3ih)
  Wbb5F_uceUp.Add(wbb4ih)
  Wbb4F_uceUp = wbb4fih.Clone()
  Wbb4F_uceUp.SetName("Wbb4F_uceUp")

 if eventTreeLocation == 'muNuEventTreeUCEDown/eventTree' :
  QCD_uceDown     = qh.Clone()
  QCD_uceDown.SetName("QCD_uceDown")
  DY_uceDown     = zih.Clone()
  DY_uceDown.SetName("DY_uceDown")
  VV_uceDown    = wwih.Clone()
  VV_uceDown.SetName("VV_uceDown")
  VV_uceDown.Add(wzih)
  VV_uceDown.Add(zzih)
  T_uceDown     = t_tih.Clone()
  T_uceDown.SetName("T_uceDown")
  T_uceDown.Add(t_sih)
  T_uceDown.Add(t_twih)
  Tbar_uceDown    = tb_tih.Clone()
  Tbar_uceDown.SetName("Tbar_uceDown")
  Tbar_uceDown.Add(tb_sih)
  Tbar_uceDown.Add(tb_twih)
  TTbar_uceDown   = tt_semiih.Clone()
  TTbar_uceDown.SetName("TTbar_uceDown")
  TTbar_uceDown.Add(tt_fullih)
  Wl_uceDown    = wlnih.Clone()
  Wl_uceDown.SetName("Wl_uceDown")
  Wl_uceDown.Add(wl1ih)
  Wl_uceDown.Add(wl2ih)
  Wl_uceDown.Add(wl3ih)
  Wl_uceDown.Add(wl4ih)
  Wl_uceDown.Add(wcnih)
  Wl_uceDown.Add(wc1ih)
  Wl_uceDown.Add(wc2ih)
  Wl_uceDown.Add(wc3ih)
  Wl_uceDown.Add(wc4ih)
  Wcc_uceDown    = wccnih.Clone()
  Wcc_uceDown.SetName("Wcc_uceDown")
  Wcc_uceDown.Add(wcc1ih)
  Wcc_uceDown.Add(wcc2ih)
  Wcc_uceDown.Add(wcc3ih)
  Wcc_uceDown.Add(wcc4ih)
  Wbb5F_uceDown   = wbbnih.Clone()
  Wbb5F_uceDown.SetName("Wbb5F_uceDown")
  Wbb5F_uceDown.Add(wbb1ih)
  Wbb5F_uceDown.Add(wbb2ih)
  Wbb5F_uceDown.Add(wbb3ih)
  Wbb5F_uceDown.Add(wbb4ih)
  Wbb4F_uceDown = wbb4fih.Clone()
  Wbb4F_uceDown.SetName("Wbb4F_uceDown")

 log.write('\n\n\n'+eventTreeLocation+'\n')
 log.write('------------------------------------------------\n')
 log.write('Non Isolated\n')
 log.write('---------------------------\n')
 log.write(' Cuts MC:      \n'+str(CutsMCn)+'\n\n')
 log.write(' Cuts MC Top:  \n'+str(CutsMCnT)+'\n\n')
 log.write(' Cuts Data:    \n'+str(CutsDatan)+'\n\n')
 log.write('Isolated\n')
 log.write('---------------------------\n')
 log.write(' Cuts MC:  \n'+str(CutsMCi)+'\n\n')
 log.write(' Cuts MC Top:  \n'+str(CutsMCiT)+'\n\n')
 log.write(' Cuts Data: \n'+str(CutsDatai)+'\n\n')
 log.write(' Cuts Wbb: \n'+str(CutsMCiwbb)+'\n\n')
 log.write(' Cuts Wcc: \n'+str(CutsMCiwcc)+'\n\n')
 log.write(' Cuts Wc: \n'+str(CutsMCiwc)+'\n\n')
 log.write(' Cuts Wl: \n'+str(CutsMCiwl)+'\n\n')
# if drawQCD:
#  log.write('Anti-Isolated Sizes\n')
#  log.write('---------------------------\n')
#  log.write(' Wn Size:--------'+str(wnnhSize)+'\n')
#  log.write(' W1 Size:--------'+str(w1nhSize)+'\n')
#  log.write(' W2 Size:--------'+str(w2nhSize)+'\n')
#  log.write(' W3 Size:--------'+str(w3nhSize)+'\n')
#  log.write(' W4 Size:--------'+str(w4nhSize)+'\n')
#  log.write(' tt Size:--------'+str(tt_seminhSize+tt_fullnhSize)+'\n')
#  log.write(' t_t Size:-------'+str(t_tnhSize)+'\n')
#  log.write(' tb_t Size:------'+str(tb_tnhSize)+'\n')
#  log.write(' t_s Size:-------'+str(t_snhSize)+'\n')
#  log.write(' tb_s Size:------'+str(tb_snhSize)+'\n')
#  log.write(' t_tw Size:------'+str(t_twnhSize)+'\n')
#  log.write(' tb_tw Size:-----'+str(tb_twnhSize)+'\n')
#  log.write(' WW Size:--------'+str(wwnhSize)+'\n')
#  log.write(' WZ Size:--------'+str(wznhSize)+'\n')
#  log.write(' ZZ Size:--------'+str(zznhSize)+'\n')
#  log.write(' Drell-Yan Size:-'+str(znhSize)+'\n')
#  log.write(' QCD Size:-------'+str(qhSize)+'\n')
#  log.write(' Data Size:      '+str(datanhSize)+'\n')
#  log.write('---------------------------\n')
#  log.write('Anti-Isolated Sizes from '+str(I)+' to '+str(F)+'\n')
#  log.write('---------------------------\n')
#  log.write(' Wn Size:--------'+str(wnnhSizePart)+'\n')
#  log.write(' W1 Size:--------'+str(w1nhSizePart)+'\n')
#  log.write(' W2 Size:--------'+str(w2nhSizePart)+'\n')
#  log.write(' W3 Size:--------'+str(w3nhSizePart)+'\n')
#  log.write(' W4 Size:--------'+str(w4nhSizePart)+'\n')
#  log.write(' tt Size:--------'+str(tt_seminhSizePart+tt_fullnhSizePart)+'\n')
#  log.write(' t_t Size:-------'+str(t_tnhSizePart)+'\n')
#  log.write(' tb_t Size:------'+str(tb_tnhSizePart)+'\n')
#  log.write(' t_s Size:-------'+str(t_snhSizePart)+'\n')
#  log.write(' tb_s Size:------'+str(tb_snhSizePart)+'\n')
#  log.write(' t_tw Size:------'+str(t_twnhSizePart)+'\n')
#  log.write(' tb_tw Size:-----'+str(tb_twnhSizePart)+'\n')
#  log.write(' WW Size:--------'+str(wwnhSizePart)+'\n')
#  log.write(' WZ Size:--------'+str(wznhSizePart)+'\n')
#  log.write(' ZZ Size:--------'+str(zznhSizePart)+'\n')
#  log.write(' Drell-Yan Size:-'+str(znhSizePart)+'\n')
#  log.write(' QCD Size:-------'+str(qhSizePart)+'\n')
#  log.write(' Data Size:      '+str(datanhSizePart)+'\n')
#  log.write('---------------------------------------------\n')
#  log.write('QCD Scale:   '+str(sf_qcd)+'\n')
#  log.write('Drell Scale: '+str(sf_drell)+'\n')
#  log.write('t Scale:     '+str(sf_st)+'\n')
#  log.write('tt Scale:    '+str(sf_ttbar)+'\n')
#  log.write('W+x Scale:   '+str(sf_wjets)+'\n')
#  log.write('---------------------------------------------\n\n')
# else:
#  log.write('no qcd drawn\n\n')
# log.write('Isolated Sizes from '+str(I)+' to '+str(F)+'\n')
# log.write('---------------------------\n')
# log.write('W:\n')
# log.write('  W+light:--------'+str(wlnihSizePart)+'\n')
# log.write('  W+light:--------'+str(wl1ihSizePart)+'\n')
# log.write('  W+light:--------'+str(wl2ihSizePart)+'\n')
# log.write('  W+light:--------'+str(wl3ihSizePart)+'\n')
# log.write('  W+light:--------'+str(wl4ihSizePart)+'\n\n')
# log.write('  W+c:------------'+str(wcnihSizePart)+'\n')
# log.write('  W+c:------------'+str(wc1ihSizePart)+'\n')
# log.write('  W+c:------------'+str(wc2ihSizePart)+'\n')
# log.write('  W+c:------------'+str(wc3ihSizePart)+'\n')
# log.write('  W+c:------------'+str(wc4ihSizePart)+'\n\n')
# log.write('  W+cc:-----------'+str(wccnihSizePart)+'\n')
# log.write('  W+cc:-----------'+str(wcc1ihSizePart)+'\n')
# log.write('  W+cc:-----------'+str(wcc2ihSizePart)+'\n')
# log.write('  W+cc:-----------'+str(wcc3ihSizePart)+'\n')
# log.write('  W+cc:-----------'+str(wcc4ihSizePart)+'\n\n')
# log.write('  W+bb:-----------'+str(wbbnihSizePart)+'\n')
# log.write('  W+bb:-----------'+str(wbb1ihSizePart)+'\n')
# log.write('  W+bb:-----------'+str(wbb2ihSizePart)+'\n')
# log.write('  W+bb:-----------'+str(wbb3ihSizePart)+'\n')
# log.write('  W+bb:-----------'+str(wbb4ihSizePart)+'\n')
# log.write('tt Size:--------'+str(tt_semiihSizePart+tt_fullihSizePart)+'\n')
# log.write('t_t Size:-------'+str(t_tihSizePart)+'\n')
# log.write('tb_t Size:------'+str(tb_tihSizePart)+'\n')
# log.write('t_s Size:-------'+str(t_sihSizePart)+'\n')
# log.write('tb_s Size:------'+str(tb_sihSizePart)+'\n')
# log.write('t_tw Size:------'+str(t_twihSizePart)+'\n')
# log.write('tb_tw Size:-----'+str(tb_twihSizePart)+'\n')
# log.write('WW Size:--------'+str(wwihSizePart)+'\n')
# log.write('WZ Size:--------'+str(wzihSizePart)+'\n')
# log.write('ZZ Size:--------'+str(zzihSizePart)+'\n')
# log.write('Drell-Yan Size:-'+str(zihSizePart)+'\n')
# if drawData:
#  log.write('Data Size:          '+str(dataihSizePart)+'\n')
# else:
#  log.write('no Data drawn\n')
# log.write('---------------------------------------------\n')
# log.write('Isolated Sizes\n')
# log.write('---------------------------\n')
# log.write('W:\n')
# log.write('  Wn+light:--------'+str(wlnihSize)+'\n')
# log.write('  W1+light:--------'+str(wl1ihSize)+'\n')
# log.write('  W2+light:--------'+str(wl2ihSize)+'\n')
# log.write('  W3+light:--------'+str(wl3ihSize)+'\n')
# log.write('  W4+light:--------'+str(wl4ihSize)+'\n\n')
# log.write('  Wn+c:------------'+str(wcnihSize)+'\n')
# log.write('  W1+c:------------'+str(wc1ihSize)+'\n')
# log.write('  W2+c:------------'+str(wc2ihSize)+'\n')
# log.write('  W3+c:------------'+str(wc3ihSize)+'\n')
# log.write('  W4+c:------------'+str(wc4ihSize)+'\n\n')
# log.write('  Wn+cc:-----------'+str(wccnihSize)+'\n')
# log.write('  W1+cc:-----------'+str(wcc1ihSize)+'\n')
# log.write('  W2+cc:-----------'+str(wcc2ihSize)+'\n')
# log.write('  W3+cc:-----------'+str(wcc3ihSize)+'\n')
# log.write('  W4+cc:-----------'+str(wcc4ihSize)+'\n\n')
# log.write('  Wn+bb:-----------'+str(wbbnihSize)+'\n')
# log.write('  W1+bb:-----------'+str(wbb1ihSize)+'\n')
# log.write('  W2+bb:-----------'+str(wbb2ihSize)+'\n')
# log.write('  W3+bb:-----------'+str(wbb3ihSize)+'\n')
# log.write('  W4+bb:-----------'+str(wbb4ihSize)+'\n')
# log.write('tt Size:--------'+str(tt_semiihSize+tt_fullihSize)+'\n')
# log.write('t_t Size:-------'+str(t_tihSize)+'\n')
# log.write('tb_t Size:------'+str(tb_tihSize)+'\n')
# log.write('t_s Size:-------'+str(t_sihSize)+'\n')
# log.write('tb_s Size:------'+str(tb_sihSize)+'\n')
# log.write('t_tw Size:------'+str(t_twihSize)+'\n')
# log.write('tb_tw Size:-----'+str(tb_twihSize)+'\n')
# log.write('WW Size:--------'+str(wwihSize)+'\n')
# log.write('WZ Size:--------'+str(wzihSize)+'\n')
# log.write('ZZ Size:--------'+str(zzihSize)+'\n')
# log.write('Drell-Yan Size:-'+str(zihSize)+'\n')
# if drawData:
#  log.write('Data Size:          '+str(dataihSize)+'\n')
# log.write('---------------------------------------------\n')
# log.write('---------------------------\n')
# log.write('Isolated Number of Entries\n')
# log.write('---------------------------\n')
# log.write('W:\n')
# log.write('  Wn+light:--------'+str(wlnihEntries)+'\n')
# log.write('  W1+light:--------'+str(wl1ihEntries)+'\n')
# log.write('  W2+light:--------'+str(wl2ihEntries)+'\n')
# log.write('  W3+light:--------'+str(wl3ihEntries)+'\n')
# log.write('  W4+light:--------'+str(wl4ihEntries)+'\n\n')
# log.write('  Wn+c:------------'+str(wcnihEntries)+'\n')
# log.write('  W1+c:------------'+str(wc1ihEntries)+'\n')
# log.write('  W2+c:------------'+str(wc2ihEntries)+'\n')
# log.write('  W3+c:------------'+str(wc3ihEntries)+'\n')
# log.write('  W4+c:------------'+str(wc4ihEntries)+'\n\n')
# log.write('  Wn+cc:-----------'+str(wccnihEntries)+'\n')
# log.write('  W1+cc:-----------'+str(wcc1ihEntries)+'\n')
# log.write('  W2+cc:-----------'+str(wcc2ihEntries)+'\n')
# log.write('  W3+cc:-----------'+str(wcc3ihEntries)+'\n')
# log.write('  W4+cc:-----------'+str(wcc4ihEntries)+'\n\n')
# log.write('  Wn+bb:-----------'+str(wbbnihEntries)+'\n')
# log.write('  W1+bb:-----------'+str(wbb1ihEntries)+'\n')
# log.write('  W2+bb:-----------'+str(wbb2ihEntries)+'\n')
# log.write('  W3+bb:-----------'+str(wbb3ihEntries)+'\n')
# log.write('  W4+bb:-----------'+str(wbb4ihEntries)+'\n')
# log.write('tt Entries:--------'+str(tt_semiihEntries+tt_fullihEntries)+'\n')
# log.write('t_t Entries:-------'+str(t_tihEntries)+'\n')
# log.write('tb_t Entries:------'+str(tb_tihEntries)+'\n')
# log.write('t_s Entries:-------'+str(t_sihEntries)+'\n')
# log.write('tb_s Entries:------'+str(tb_sihEntries)+'\n')
# log.write('t_tw Entries:------'+str(t_twihEntries)+'\n')
# log.write('tb_tw Entries:-----'+str(tb_twihEntries)+'\n')
# log.write('WW Entries:--------'+str(wwihEntries)+'\n')
# log.write('WZ Entries:--------'+str(wzihEntries)+'\n')
# log.write('ZZ Entries:--------'+str(zzihEntries)+'\n')
# log.write('Drell-Yan Entries:-'+str(zihEntries)+'\n')
# if drawData:
#  log.write('Data Entries:          '+str(dataihEntries)+'\n')
# log.write('---------------------------------------------\n')
# log.write('---------------------------------------------\n')
 #log.write('DataCard Numbers\n')
 #log.write('---------------------------\n')
 #if drawData:
 # log.write('Data Size:      '+str(dataihSize)+'\n')
 #log.write('Wbb Size:       '+str(wbbnihSize+wbb1ihSize+wbb2ihSize+wbb3ihSize+wbb4ihSize)+'\n')
 #log.write('Wcc Size:       '+str(wccnihSize+wcc1ihSize+wcc2ihSize+wcc3ihSize+wcc4ihSize)+'\n')
 #log.write('TTbar Size:     '+str(tt_semiihSize+tt_fullihSize)+'\n')
 #log.write('T Size:         '+str(t_tihSize+t_sihSize)+'\n')
 #log.write('Tbar Size:      '+str(tb_tihSize+tb_sihSize)+'\n')
 #log.write('T_tW Size:      '+str(t_twihSize+tb_twihSize)+'\n')
 #log.write('Drell-Yan Size: '+str(zihSize)+'\n')
 #log.write('VV Size:        '+str(wwihSize+wzihSize+zzihSize)+'\n')
 #log.write('QCD Size:       '+str(qhSize)+'\n')

 
 if eventTreeLocation == 'muNuEventTree/eventTree' :
  znhBup.Delete()	
  wwnhBup.Delete()	
  wznhBup.Delete()	
  zznhBup.Delete()	
  t_tnhBup.Delete()	
  tb_tnhBup.Delete()	
  t_snhBup.Delete()	
  tb_snhBup.Delete()	
  t_twnhBup.Delete()	
  tb_twnhBup.Delete()	
  tt_seminhBup.Delete()	
  tt_fullnhBup.Delete()	
  wnnhBup.Delete()	
  w1nhBup.Delete()	
  w2nhBup.Delete()	
  w3nhBup.Delete()	
  w4nhBup.Delete()	
  znhBdn.Delete()	
  wwnhBdn.Delete()	
  wznhBdn.Delete()	
  zznhBdn.Delete()	
  t_tnhBdn.Delete()	
  tb_tnhBdn.Delete()	
  t_snhBdn.Delete()	
  tb_snhBdn.Delete()	
  t_twnhBdn.Delete()	
  tb_twnhBdn.Delete()	
  tt_seminhBdn.Delete()	
  tt_fullnhBdn.Delete()	
  wnnhBdn.Delete()	
  w1nhBdn.Delete()	
  w2nhBdn.Delete()	
  w3nhBdn.Delete()	
  w4nhBdn.Delete()	
  zihBup.Delete()	
  wwihBup.Delete()	
  wzihBup.Delete()	
  zzihBup.Delete()	
  t_tihBup.Delete()	
  tb_tihBup.Delete()	
  t_sihBup.Delete()	
  tb_sihBup.Delete()	
  t_twihBup.Delete()	
  tb_twihBup.Delete()	
  tt_semiihBup.Delete()	
  tt_fullihBup.Delete()	
  wlnihBup.Delete()	
  wcnihBup.Delete()	
  wccnihBup.Delete()	
  wbbnihBup.Delete()	
  wl1ihBup.Delete()	
  wc1ihBup.Delete()	
  wcc1ihBup.Delete()	
  wbb1ihBup.Delete()	
  wl2ihBup.Delete()	
  wc2ihBup.Delete()	
  wcc2ihBup.Delete()	
  wbb2ihBup.Delete()	
  wl3ihBup.Delete()	
  wc3ihBup.Delete()	
  wcc3ihBup.Delete()	
  wbb3ihBup.Delete()	
  wl4ihBup.Delete()	
  wc4ihBup.Delete()	
  wcc4ihBup.Delete()	
  wbb4ihBup.Delete()	
  wbb4fihBup.Delete()
  zihBdn.Delete()	
  wwihBdn.Delete()	
  wzihBdn.Delete()	
  zzihBdn.Delete()	
  t_tihBdn.Delete()	
  tb_tihBdn.Delete()	
  t_sihBdn.Delete()	
  tb_sihBdn.Delete()	
  t_twihBdn.Delete()	
  tb_twihBdn.Delete()	
  tt_semiihBdn.Delete()	
  tt_fullihBdn.Delete()	
  wlnihBdn.Delete()	
  wcnihBdn.Delete()	
  wccnihBdn.Delete()	
  wbbnihBdn.Delete()	
  wl1ihBdn.Delete()	
  wc1ihBdn.Delete()	
  wcc1ihBdn.Delete()	
  wbb1ihBdn.Delete()	
  wl2ihBdn.Delete()	
  wc2ihBdn.Delete()	
  wcc2ihBdn.Delete()	
  wbb2ihBdn.Delete()	
  wl3ihBdn.Delete()	
  wc3ihBdn.Delete()	
  wcc3ihBdn.Delete()	
  wbb3ihBdn.Delete()	
  wl4ihBdn.Delete()	
  wc4ihBdn.Delete()	
  wcc4ihBdn.Delete()	
  wbb4ihBdn.Delete()
  wbb4fihBdn.Delete()

 znh.Delete()    #Drell
 t_tnh.Delete()  #Single Top
 tb_tnh.Delete()
 t_snh.Delete()
 tb_snh.Delete()
 t_twnh.Delete()
 tb_twnh.Delete()
 wwnh.Delete()   #Diboson
 wznh.Delete()
 zznh.Delete()
 if eventTreeLocation == 'muNuEventTree/eventTree' :
  tt_seminhDn.Delete()  #TTbar
  tt_fullnhDn.Delete()  #TTbar
  tt_seminhUp.Delete()  #TTbar
  tt_fullnhUp.Delete()  #TTbar
 tt_seminh.Delete()  #TTbar
 tt_fullnh.Delete()  #TTbar
 wnnh.Delete()   #W
 w1nh.Delete()
 w2nh.Delete()
 w3nh.Delete()
 w4nh.Delete()
 zih.Delete()
 wwih.Delete()
 wzih.Delete()
 zzih.Delete()
 t_tih.Delete()
 tb_tih.Delete()
 t_sih.Delete()
 tb_sih.Delete()
 t_twih.Delete()
 tb_twih.Delete()
 if eventTreeLocation == 'muNuEventTree/eventTree' :
  tt_semiihDn.Delete()
  tt_fullihDn.Delete()
  tt_semiihUp.Delete()
  tt_fullihUp.Delete()
 tt_semiih.Delete()
 tt_fullih.Delete()
 wlnih.Delete()
 wl1ih.Delete()
 wl2ih.Delete()
 wl3ih.Delete()
 wl4ih.Delete()
 wcnih.Delete()
 wc1ih.Delete()
 wc2ih.Delete()
 wc3ih.Delete()
 wc4ih.Delete()
 wccnih.Delete()
 wcc1ih.Delete()
 wcc2ih.Delete()
 wcc3ih.Delete()
 wcc4ih.Delete()
 wbbnih.Delete()
 wbb1ih.Delete()
 wbb2ih.Delete()
 wbb3ih.Delete()
 wbb4ih.Delete()
 wbb4fih.Delete()
 
datanh.Delete()
print(".log written")
log.close()

outFile.Write()
print('')
print('Your File is here: '+path+extraName+'_'+leaf+'.root')
print('')
 
