#!/usr/bin/env python
'''
Rename histograms for 8TeV datacards 
Author: T.M.Perry
'''

import ROOT
from ROOT import *

inFilename = 'Datacard_oldGT_NoSH_2j2525_2bt_highestJetPt.root'
inFile = TFile(inFilename)

outFile=gROOT.FindObject('Renamed_'+inFilename)
if outFile : outFile.Close()
outFile = TFile('Renamed_'+inFilename,'RECREATE','renamed histograms')

# Unshifted
data_obs_INFILE = inFile.Get("dataih")
data_obs = data_obs_INFILE.Clone()
data_obs.SetName("data_obs")

Wbb_INFILE = inFile.Get("wbbihNo")
Wbb = Wbb_INFILE.Clone()
Wbb.SetName("Wbb")
TOP_INFILE = inFile.Get("ttbihNo")
TOP = TOP_INFILE.Clone()
TOP.SetName("TOP")
Wcc_INFILE = inFile.Get("wccihNo")
Wcc = Wcc_INFILE.Clone()
Wcc.SetName("Wcc")
T_INFILE = inFile.Get("tihNo")
T = T_INFILE.Clone()
T.SetName("T")
Tbar_INFILE = inFile.Get("tbihNo")
Tbar = Tbar_INFILE.Clone()
Tbar.SetName("Tbar")
tW_INFILE = inFile.Get("t_twihNo")
tW = tW_INFILE.Clone()
tW.SetName("tW")
Z_jets_INFILE = inFile.Get("zihNo")
Z_jets = Z_jets_INFILE.Clone()
Z_jets.SetName("Z_jets")
WZ_INFILE = inFile.Get("vvihNo")
WZ = WZ_INFILE.Clone()
WZ.SetName("WZ")
QCD_INFILE = inFile.Get("qhNo")
QCD = QCD_INFILE.Clone()
QCD.SetName("QCD")

# Muon Up
Wbb_INFILE_muonUp = inFile.Get("wbbihUp")
Wbb_muonUp = Wbb_INFILE_muonUp.Clone()
Wbb_muonUp.SetName("Wbb_muonUp")
Wcc_INFILE_muonUp = inFile.Get("wccihUp")
Wcc_muonUp = Wcc_INFILE_muonUp.Clone()
Wcc_muonUp.SetName("Wcc_muonUp")
TOP_INFILE_muonUp = inFile.Get("ttbihUp")
TOP_muonUp = TOP_INFILE_muonUp.Clone()
TOP_muonUp.SetName("TOP_muonUp")
T_INFILE_muonUp = inFile.Get("tihUp")
T_muonUp = T_INFILE_muonUp.Clone()
T_muonUp.SetName("T_muonUp")
Tbar_INFILE_muonUp = inFile.Get("tbihUp")
Tbar_muonUp = Tbar_INFILE_muonUp.Clone()
Tbar_muonUp.SetName("Tbar_muonUp")
tW_INFILE_muonUp = inFile.Get("t_twihUp")
tW_muonUp = tW_INFILE_muonUp.Clone()
tW_muonUp.SetName("tW_muonUp")
Z_jets_INFILE_muonUp = inFile.Get("zihUp")
Z_jets_muonUp = Z_jets_INFILE_muonUp.Clone()
Z_jets_muonUp.SetName("Z_jets_muonUp")
WZ_INFILE_muonUp = inFile.Get("vvihUp")
WZ_muonUp = WZ_INFILE_muonUp.Clone()
WZ_muonUp.SetName("WZ_muonUp")

# Muon Down
Wbb_INFILE_muonDown = inFile.Get("wbbihDn")
Wbb_muonDown = Wbb_INFILE_muonDown.Clone()
Wbb_muonDown.SetName("Wbb_muonDown")
Wcc_INFILE_muonDown = inFile.Get("wccihDn")
Wcc_muonDown = Wcc_INFILE_muonDown.Clone()
Wcc_muonDown.SetName("Wcc_muonDown")
TOP_INFILE_muonDown = inFile.Get("ttbihDn")
TOP_muonDown = TOP_INFILE_muonDown.Clone()
TOP_muonDown.SetName("TOP_muonDown")
T_INFILE_muonDown = inFile.Get("tihDn")
T_muonDown = T_INFILE_muonDown.Clone()
T_muonDown.SetName("T_muonDown")
Tbar_INFILE_muonDown = inFile.Get("tbihDn")
Tbar_muonDown = Tbar_INFILE_muonDown.Clone()
Tbar_muonDown.SetName("Tbar_muonDown")
tW_INFILE_muonDown = inFile.Get("t_twihDn")
tW_muonDown = tW_INFILE_muonDown.Clone()
tW_muonDown.SetName("tW_muonDown")
Z_jets_INFILE_muonDown = inFile.Get("zihDn")
Z_jets_muonDown = Z_jets_INFILE_muonDown.Clone()
Z_jets_muonDown.SetName("Z_jets_muonDown")
WZ_INFILE_muonDown = inFile.Get("vvihDn")
WZ_muonDown = WZ_INFILE_muonDown.Clone()
WZ_muonDown.SetName("WZ_muonDown")

# Jet Up
Wbb_INFILE_jetUp = inFile.Get("wbbihJUp")
Wbb_jetUp = Wbb_INFILE_jetUp.Clone()
Wbb_jetUp.SetName("Wbb_jetUp")
Wcc_INFILE_jetUp = inFile.Get("wccihJUp")
Wcc_jetUp = Wcc_INFILE_jetUp.Clone()
Wcc_jetUp.SetName("Wcc_jetUp")
TOP_INFILE_jetUp = inFile.Get("ttbihJUp")
TOP_jetUp = TOP_INFILE_jetUp.Clone()
TOP_jetUp.SetName("TOP_jetUp")
T_INFILE_jetUp = inFile.Get("tihJUp")
T_jetUp = T_INFILE_jetUp.Clone()
T_jetUp.SetName("T_jetUp")
Tbar_INFILE_jetUp = inFile.Get("tbihJUp")
Tbar_jetUp = Tbar_INFILE_jetUp.Clone()
Tbar_jetUp.SetName("Tbar_jetUp")
tW_INFILE_jetUp = inFile.Get("t_twihJUp")
tW_jetUp = tW_INFILE_jetUp.Clone()
tW_jetUp.SetName("tW_jetUp")
Z_jets_INFILE_jetUp = inFile.Get("zihJUp")
Z_jets_jetUp = Z_jets_INFILE_jetUp.Clone()
Z_jets_jetUp.SetName("Z_jets_jetUp")
WZ_INFILE_jetUp = inFile.Get("vvihJUp")
WZ_jetUp = WZ_INFILE_jetUp.Clone()
WZ_jetUp.SetName("WZ_jetUp")

# Jet Down
Wbb_INFILE_jetDown = inFile.Get("wbbihJDn")
Wbb_jetDown = Wbb_INFILE_jetDown.Clone()
Wbb_jetDown.SetName("Wbb_jetDown")
Wcc_INFILE_jetDown = inFile.Get("wccihJDn")
Wcc_jetDown = Wcc_INFILE_jetDown.Clone()
Wcc_jetDown.SetName("Wcc_jetDown")
TOP_INFILE_jetDown = inFile.Get("ttbihJDn")
TOP_jetDown = TOP_INFILE_jetDown.Clone()
TOP_jetDown.SetName("TOP_jetDown")
T_INFILE_jetDown = inFile.Get("tihJDn")
T_jetDown = T_INFILE_jetDown.Clone()
T_jetDown.SetName("T_jetDown")
Tbar_INFILE_jetDown = inFile.Get("tbihJDn")
Tbar_jetDown = Tbar_INFILE_jetDown.Clone()
Tbar_jetDown.SetName("Tbar_jetDown")
tW_INFILE_jetDown = inFile.Get("t_twihJDn")
tW_jetDown = tW_INFILE_jetDown.Clone()
tW_jetDown.SetName("tW_jetDown")
Z_jets_INFILE_jetDown = inFile.Get("zihJDn")
Z_jets_jetDown = Z_jets_INFILE_jetDown.Clone()
Z_jets_jetDown.SetName("Z_jets_jetDown")
WZ_INFILE_jetDown = inFile.Get("vvihJDn")
WZ_jetDown = WZ_INFILE_jetDown.Clone()
WZ_jetDown.SetName("WZ_jetDown")

# UCE Up
Wbb_INFILE_jetUCEUp = inFile.Get("wbbihUUp")
Wbb_jetUCEUp = Wbb_INFILE_jetUCEUp.Clone()
Wbb_jetUCEUp.SetName("Wbb_jetUCEUp")
Wcc_INFILE_jetUCEUp = inFile.Get("wccihUUp")
Wcc_jetUCEUp = Wcc_INFILE_jetUCEUp.Clone()
Wcc_jetUCEUp.SetName("Wcc_jetUCEUp")
TOP_INFILE_jetUCEUp = inFile.Get("ttbihUUp")
TOP_jetUCEUp = TOP_INFILE_jetUCEUp.Clone()
TOP_jetUCEUp.SetName("TOP_jetUCEUp")
T_INFILE_jetUCEUp = inFile.Get("tihUUp")
T_jetUCEUp = T_INFILE_jetUCEUp.Clone()
T_jetUCEUp.SetName("T_jetUCEUp")
Tbar_INFILE_jetUCEUp = inFile.Get("tbihUUp")
Tbar_jetUCEUp = Tbar_INFILE_jetUCEUp.Clone()
Tbar_jetUCEUp.SetName("Tbar_jetUCEUp")
tW_INFILE_jetUCEUp = inFile.Get("t_twihUUp")
tW_jetUCEUp = tW_INFILE_jetUCEUp.Clone()
tW_jetUCEUp.SetName("tW_jetUCEUp")
Z_jets_INFILE_jetUCEUp = inFile.Get("zihUUp")
Z_jets_jetUCEUp = Z_jets_INFILE_jetUCEUp.Clone()
Z_jets_jetUCEUp.SetName("Z_jets_jetUCEUp")
WZ_INFILE_jetUCEUp = inFile.Get("vvihUUp")
WZ_jetUCEUp = WZ_INFILE_jetUCEUp.Clone()
WZ_jetUCEUp.SetName("WZ_jetUCEUp")

# UCE Down
Wbb_INFILE_jetUCEDown = inFile.Get("wbbihUDn")
Wbb_jetUCEDown = Wbb_INFILE_jetUCEDown.Clone()
Wbb_jetUCEDown.SetName("Wbb_jetUCEDown")
Wcc_INFILE_jetUCEDown = inFile.Get("wccihUDn")
Wcc_jetUCEDown = Wcc_INFILE_jetUCEDown.Clone()
Wcc_jetUCEDown.SetName("Wcc_jetUCEDown")
TOP_INFILE_jetUCEDown = inFile.Get("ttbihUDn")
TOP_jetUCEDown = TOP_INFILE_jetUCEDown.Clone()
TOP_jetUCEDown.SetName("TOP_jetUCEDown")
T_INFILE_jetUCEDown = inFile.Get("tihUDn")
T_jetUCEDown = T_INFILE_jetUCEDown.Clone()
T_jetUCEDown.SetName("T_jetUCEDown")
Tbar_INFILE_jetUCEDown = inFile.Get("tbihUDn")
Tbar_jetUCEDown = Tbar_INFILE_jetUCEDown.Clone()
Tbar_jetUCEDown.SetName("Tbar_jetUCEDown")
tW_INFILE_jetUCEDown = inFile.Get("t_twihUDn")
tW_jetUCEDown = tW_INFILE_jetUCEDown.Clone()
tW_jetUCEDown.SetName("tW_jetUCEDown")
Z_jets_INFILE_jetUCEDown = inFile.Get("zihUDn")
Z_jets_jetUCEDown = Z_jets_INFILE_jetUCEDown.Clone()
Z_jets_jetUCEDown.SetName("Z_jets_jetUCEDown")
WZ_INFILE_jetUCEDown = inFile.Get("vvihUDn")
WZ_jetUCEDown = WZ_INFILE_jetUCEDown.Clone()
WZ_jetUCEDown.SetName("WZ_jetUCEDown")

outFile.Write()
